package:
  name: atlantis
  version: 0.27.1
  epoch: 0
  description: Terraform Pull Request Automation
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - libcap-utils
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/runatlantis/atlantis
      tag: v${{package.version}}
      expected-commit: da67e7d9af442b7927edec38515133c3c494bdfa

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0
      go-version: "1.21"

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: atlantis
      ldflags: -w -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

  # This must come after strip!
  - runs: |
      setcap "cap_net_bind_service=+ep" "${{targets.destdir}}"/usr/bin/atlantis

update:
  enabled: true
  github:
    identifier: runatlantis/atlantis
    strip-prefix: v
    use-tag: true
