package:
  name: aws-c-sdkutils
  version: 0.1.14
  epoch: 0
  description: C99 library implementing AWS SDK specific utilities
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-c-common-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5acb6dd916511a3dff14faea43385d117d755f4ad4a9c52314cc74e427398f37
      uri: https://github.com/awslabs/aws-c-sdkutils/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-c-sdkutils-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-sdkutils "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-sdkutils
    description: aws-c-sdkutils dev

update:
  enabled: true
  github:
    identifier: awslabs/aws-c-sdkutils
    strip-prefix: v
    use-tag: true
