package:
  name: binutils
  version: "2.41"
  epoch: 1
  description: "GNU binutils"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - isl
      - texinfo
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/binutils/binutils-${{package.version}}.tar.gz
      expected-sha256: 48d00a8dc73aa7d2394a7dc069b96191d95e8de8f0da6dc91da5cce655c20e45

  - name: 'Configure binutils'
    runs: |
      ./configure \
        --prefix=/usr \
        --build=$(./config.guess) \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --disable-nls \
        --disable-werror \
        --disable-multilib \
        --disable-gprofng \
        --enable-deterministic-archives \
        --enable-ld=default \
        --enable-gold \
        --enable-plugins \
        --enable-default-execstack=no \
        --enable-default-hash-style=gnu \
        --enable-textrel-check=error

  - uses: autoconf/make

  - uses: autoconf/make-install

  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

  - uses: strip

subpackages:
  - name: "binutils-dev"
    description: "binutils development headers"
    pipeline:
      - uses: split/dev

  - name: "binutils-gold"
    description: "binutils (gold linker)"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/ld.gold "${{targets.subpkgdir}}"/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 7981
