package:
  name: bmake
  version: "20240602"
  epoch: 0
  description: Portable version of the NetBSD make build tool
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - tzdata

pipeline:
  - uses: fetch
    with:
      expected-sha256: 44a0f7b0cecd71dc43a03c8fd5eda6d159e0d7e1302f669cc03203e75dde7b9b
      uri: http://www.crufty.net/ftp/pub/sjg/bmake-${{package.version}}.tar.gz
      strip-components: 0

  - runs: |
      ./bmake/boot-strap \
        --prefix=/usr \
        --install-destdir=${{targets.destdir}} \
        --install

subpackages:
  - name: bmake-doc
    pipeline:
      - uses: split/manpages
    description: bmake manpages

update:
  enabled: true
  release-monitor:
    identifier: 208
