package:
  name: byobu
  version: "6.9"
  epoch: 0
  description: "open source text-based window manager and terminal multiplexer"
  copyright:
    - license: GPL-3.0
  dependencies:
    runtime:
      - gawk
      - iproute2
      - posix-libc-utils
      - python3
      - tmux

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dustinkirkland/byobu
      expected-commit: 6308b188cec8eb45fa993506de784bf2dc1b8e48
      tag: ${{package.version}}

  - runs: autoreconf -vif

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: dustinkirkland/byobu
    use-tag: true
