package:
  name: bzip2
  version: 1.0.8
  epoch: 6
  description: "a library implementing the bzip2 compression algorithms"
  copyright:
    - license: MPL-2.0 AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - make
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://sourceware.org/pub/bzip2/bzip2-${{package.version}}.tar.gz
      expected-sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269

  - uses: patch
    with:
      patches: bzip2-1.0.2-progress.patch

  - uses: patch
    with:
      patches: bzip2-1.0.3-no-test.patch

  - uses: patch
    with:
      patches: bzip2-1.0.4-makefile-CFLAGS.patch

  - uses: patch
    with:
      patches: bzip2-1.0.4-man-links.patch

  - uses: patch
    with:
      patches: saneso.patch

  - runs: |
      sed -i \
        -e 's:\$(PREFIX)/man:\$(PREFIX)/share/man:g' \
        -e 's:ln -s -f $(PREFIX)/bin/:ln -s :' \
        Makefile

      sed -i \
        -e "s:1\.0\.4:${{package.version}}:" \
        bzip2.1 bzip2.txt Makefile-libbz2_so manual.*

  - runs: |
      make -f Makefile-libbz2_so all
      make all

  - runs: |
      make PREFIX="${{targets.destdir}}/usr" install

  - uses: strip

subpackages:
  - name: "libbz2-1"
    description: bzip2 shared library
    pipeline:
      - runs: |
          install -D libbz2.so.${{package.version}} "${{targets.subpkgdir}}"/usr/lib/libbz2.so.${{package.version}}
          ln -s libbz2.so.${{package.version}} "${{targets.subpkgdir}}"/usr/lib/libbz2.so.1

  - name: "bzip2-dev"
    description: "bzip2 headers"
    pipeline:
      - uses: split/dev
      - runs: |
          ln -s libbz2.so.1 "${{targets.subpkgdir}}"/usr/lib/libbz2.so

update:
  enabled: true
  release-monitor:
    identifier: 237
