package:
  name: cert-manager-1.11
  version: 1.11.5
  epoch: 10
  description: Automatically provision and manage TLS certificates in Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cert-manager=1.11.999

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - jq
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b1d501c85d97afd2adde2e86c2b119ac060caece
      repository: https://github.com/cert-manager/cert-manager
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel@v1.21.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0 go.opentelemetry.io/otel/sdk@v1.21.0 github.com/docker/docker@v24.0.7 oras.land/oras-go@v1.2.4 github.com/cyphar/filepath-securejoin@v0.2.4 golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11
      replaces: go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp=go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0

  - runs: |
      make CTR=make _bin/server/controller-linux-$(go env GOARCH)
      make CTR=make _bin/server/webhook-linux-$(go env GOARCH)
      make CTR=make _bin/server/cainjector-linux-$(go env GOARCH)
      make CTR=make _bin/server/acmesolver-linux-$(go env GOARCH)

      mkdir -p ${{targets.destdir}}/usr/bin
      mv _bin/server/* ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: ${{package.name}}-controller
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/controller-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/controller
    dependencies:
      provides:
        - cert-manager-controller=1.11.999 # This is because we had a 1.11.2 cert-manager package, remove in 1.13+

  - name: ${{package.name}}-webhook
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/webhook-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/webhook
    dependencies:
      provides:
        - cert-manager-webhook=1.11.999 # This is because we had a 1.11.2 cert-manager package, remove in 1.13+

  - name: ${{package.name}}-cainjector
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/cainjector-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/cainjector
    dependencies:
      provides:
        - cert-manager-cainjector=1.11.999 # This is because we had a 1.11.2 cert-manager package, remove in 1.13+

  - name: ${{package.name}}-acmesolver
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/acmesolver-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/acmesolver
    dependencies:
      provides:
        - cert-manager-acmesolver=1.11.999 # This is because we had a 1.11.2 cert-manager package, remove in 1.13+

  - name: cmctl-1.11
    pipeline:
      - runs: |
          make CTR=make _bin/cmctl/cmctl-linux-$(go env GOARCH)
      - runs: |
          install -Dm755 _bin/cmctl/cmctl-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/cmctl
      - uses: strip
    dependencies:
      provides:
        - cmctl=1.11.999 # This is because we had a 1.11.2 cert-manager package, remove in 1.13+

update:
  enabled: true
  github:
    identifier: cert-manager/cert-manager
    strip-prefix: v
    tag-filter: v1.11.
    use-tag: true
