package:
  name: chartmuseum
  version: 0.16.2
  epoch: 0
  description: helm chart repository server
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8795e9930ad1f88f8c20426368327b0e500adcda
      repository: https://github.com/helm/chartmuseum
      tag: v${{package.version}}

  - runs: |
      CGO_ENABLED=0 go build --ldflags="-s -w -X main.Version=${{package.version}} \
        -X main.Revision=$(git rev-parse --short HEAD)" \
        -o "${{targets.destdir}}/usr/bin/chartmuseum" \
        cmd/chartmuseum/main.go

  - uses: strip

update:
  enabled: true
  github:
    identifier: helm/chartmuseum
    strip-prefix: v
