package:
  name: chromium
  version: 122.0.6250.1
  epoch: 4
  description: "Open souce version of Google's chrome web browser"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - alsa-lib-dev
      - bash
      - bison
      - brotli-dev
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - cairo-dev
      - cups-dev
      - curl
      - curl-dev
      - dav1d-dev
      - dbus-glib-dev
      - elfutils
      - elfutils-dev
      - eudev-dev
      - ffmpeg-dev
      - findutils
      - flac-dev
      - flex
      - freetype-dev
      - git
      - glib-dev
      - gn
      - gperf
      - gzip
      - harfbuzz-dev
      - hwdata-dev
      - krb5-dev
      - lcms2-dev
      - libbsd-dev
      - libcap-dev
      - libevent-dev
      - libffi-dev
      - libgcrypt-dev
      - libjpeg-turbo-dev
      - libnss-dev
      - libsecret-dev
      - libusb-dev
      - libva-dev
      - libwebp-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage
      - libxinerama-dev
      - libxkbcommon
      - libxml2-dev
      - libxrandr-dev
      - libxslt-dev
      - libxtst
      - linux-headers
      - mesa-dev
      - mesa-gbm
      - opus-dev
      - pango
      - pciutils-dev
      - perl
      - pulseaudio-dev
      - py3-httplib2
      - py3-setuptools
      - python3
      - rust
      - samurai
      - speex-dev
      - sqlite-dev
      - wget
      - xcb-proto
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      # === INFO === Initial git clone: takes ~3 minutes, needs 6GB disk
      repository: https://chromium.googlesource.com/chromium/src.git
      tag: ${{package.version}}
      depth: 1
      expected-commit: 553d92272085528d3d2c898c9263714e8ad3345b
      destination: /home/src

  - runs: |
      # I never can remember where I am, at the beginning of the build step...
      set -x
      cd /home
      ls -halF /home/src
      du -sh /home/src
      df -h .
      # Mostly following: https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md
      # === INFO === Fetch tools: takes about 2 seconds, 63 MB of disk
      # depot_tools must be at a directory above chromium's src
      cd /home
      time git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
      du -sh /home/depot_tools
      export PATH="$PATH:/home/depot_tools"
      # .gclient must be in one directory above chromium's src
      cat <<EOF >/home/.gclient
      # Setup a .gclient config (handled by 'fetch' in upstream instructions)
      solutions = [
        { "name"        : "src",
          "url"         : "https://chromium.googlesource.com/chromium/src.git",
          "managed": False,
          "custom_deps": {},
          "custom_vars": {},
        },
      ]
      EOF
      cat /home/.gclient
      # === INFO === Sync dependencies: takes about 11 minutes, requires 30 GB of disk
      # go back into our chromium src directory
      cd /home/src
      time gclient sync --no-history
      du -sh /home/src
      # === INFO === Generate config: takes about 30 minutes /
      cd /home/src
      time gn gen /home/src/out/Default --args="is_debug=false"
      du -sh .
      # === INFO === Compile: takes about 3 hours, 60 GB of disk (on a 32xXeon, 128GBxRAM, 2TBxNVME system)
      cd /home/src
      time autoninja -C /home/src/out/Default chrome chromedriver chrome_sandbox
      # === INFO === Install the binaries and libraries
      cd /home/src/out/Default
      mkdir -p ${{targets.destdir}}/usr/bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv *.so* ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chrome ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chrome_sandbox ${{targets.destdir}}/usr/lib/${{package.name}}
      mv chromedriver ${{targets.destdir}}/usr/lib/${{package.name}}
      # resources
      mv snapshot_blob.bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv v8_context_snapshot.bin ${{targets.destdir}}/usr/lib/${{package.name}}
      mv icudtl.dat ${{targets.destdir}}/usr/lib/${{package.name}}
      mv xdg-mime ${{targets.destdir}}/usr/lib/${{package.name}}
      mv xdg-settings ${{targets.destdir}}/usr/lib/${{package.name}}
      mv vk_swiftshader_icd.json ${{targets.destdir}}/usr/lib/${{package.name}}
      mv *.pak ${{targets.destdir}}/usr/lib/${{package.name}}
      mv locales ${{targets.destdir}}/usr/lib/${{package.name}}
      # links
      ln -sf /usr/lib/${{package.name}}/chrome ${{targets.destdir}}/usr/bin/chromium-browser
      ln -sf chromium-browser ${{targets.destdir}}/usr/bin/chromium
      mkdir -p ${{targets.destdir}}/etc/chromium

  - uses: strip

subpackages:
  - name: ${{package.name}}-qt
    options:
      no-depends: true
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/${{package.name}}
          mv ${{targets.destdir}}/usr/lib/${{package.name}}/*qt* ${{targets.subpkgdir}}/usr/lib/${{package.name}}
  - name: ${{package.name}}-lang
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/${{package.name}}
          mv ${{targets.destdir}}/usr/lib/${{package.name}}/locales ${{targets.subpkgdir}}/usr/lib/${{package.name}}


test:
  environment:
    contents:
      packages:
        - chromium
  pipeline:
    - runs: |
        chrome --no-sandbox --headless --disable-gpu --dump-dom https://www.chromestatus.com
