package:
  name: cilium
  version: 1.14.5
  epoch: 1
  description: Cilium is a networking, observability, and security solution with an eBPF-based dataplane
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bpftool
      # cilium does compilations at runtime on the node.
      - clang
      - cni-plugins-main
      - iproute2
      - ipset
      - iptables
      - kmod
      - llvm15
      - llvm15-tools

environment:
  contents:
    packages:
      - build-base
      - busybox
      - clang
      - coreutils # for GNU install
      - git
      - go
      - grep
      - iptables # for cilium-iptables
      - llvm15
      - llvm15-tools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium
      tag: v${{package.version}}
      expected-commit: 85db28befd47d150ac6a4a89b58c562e76f65c6e

  - uses: patch
    with:
      patches: loopback-location.patch

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.1 golang.org/x/crypto@v0.17.0
      go-version: "1.21"

  - runs: |
      # Remove groupadd from Makefile: it's not doing anything useful in
      # a package build anyway, and it's not available in busybox.
      find . -name Makefile -exec sed -i '/groupadd/d' {} \;

      DESTDIR=${{targets.destdir}} DISABLE_ENVOY_INSTALLATION=1 make build-container
      DESTDIR=${{targets.destdir}} DISABLE_ENVOY_INSTALLATION=1 make install-container

  - uses: strip

subpackages:
  - name: ${{package.name}}-container-init
    description: init scripts for cilium
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          cp images/cilium/init-container.sh \
             plugins/cilium-cni/install-plugin.sh \
             plugins/cilium-cni/cni-uninstall.sh \
            ${{targets.subpkgdir}}/usr/bin

  - name: ${{package.name}}-container-init-compat
    description: init scripts for cilium
    dependencies:
      runtime:
        - ${{package.name}}-container-init
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/init-container.sh ${{targets.subpkgdir}}/init-container.sh
          ln -sf /usr/bin/install-plugin.sh ${{targets.subpkgdir}}/install-plugin.sh
          ln -sf /usr/bin/cni-uninstall.sh ${{targets.subpkgdir}}/cni-uninstall.sh

  - name: ${{package.name}}-iptables
    description: iptables compatibility package for cilium
    dependencies:
      runtime:
        - iptables
    pipeline:
      - runs: |
          # This script generates a wrapper based on the version
          # of iptables provided by the build environment.
          ./images/runtime/iptables-wrapper-installer.sh
          mkdir -p ${{targets.subpkgdir}}/sbin
          mv /sbin/iptables-wrapper ${{targets.subpkgdir}}/sbin/iptables-wrapper
      - uses: strip

  - name: ${{package.name}}-operator-generic
    description: Generic operator for cilium
    dependencies:
      runtime:
        - gops
    pipeline:
      - runs: |
          cd /home/build/operator
          make cilium-operator-generic
          DESTDIR=${{targets.subpkgdir}} make install-generic
      - uses: strip

  - name: hubble-relay
    description: Hubble relay
    pipeline:
      - runs: |
          cd /home/build/hubble-relay
          make hubble-relay
          DESTDIR=${{targets.subpkgdir}} make install
      - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/cilium
    strip-prefix: v
