package:
  name: conftest
  version: 0.53.0
  epoch: 0
  description: Write tests against structured configuration data using the Open Policy Agent Rego query language
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cue

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 493cfd55b0a2745d918d3564f7a8b64c0ba776e8
      repository: https://github.com/open-policy-agent/conftest
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -X github.com/open-policy-agent/conftest/internal/commands.version=${{package.version}}
      modroot: .
      output: conftest
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: open-policy-agent/conftest
    strip-prefix: v
