package:
  name: containerd
  version: 1.7.12
  epoch: 2
  description: An open and reliable container runtime
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - runc

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 71909c1814c544ac47ab91d2e8b84718e517bb99
      repository: https://github.com/containerd/containerd
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel/sdk@v1.20.0

  - runs: |
      make VERSION="v${{package.version}}"

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/containerd
      ./bin/containerd config default > "${{targets.destdir}}"/etc/containerd/config.toml

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      install -sm755 ./bin/* "${{targets.destdir}}"/usr/bin/

  - uses: strip

data:
  - name: bins
    items:
      ctr: client for containerd
      containerd-stress: stress utility
      containerd-shim: shim
      containerd-shim-runc-v1: runc shim v1
      containerd-shim-runc-v2: runc shim v2

subpackages:
  - range: bins
    name: ${{range.key}}
    description: ${{range.value}}
    pipeline:
      - runs: |
          install -Dm755 "${{targets.destdir}}"/usr/bin/${{range.key}} "${{targets.subpkgdir}}"/usr/bin/${{range.key}}

update:
  enabled: true
  github:
    identifier: containerd/containerd
    strip-prefix: v
