package:
  name: crane
  version: 0.18.0
  epoch: 0
  description: Tool for interacting with remote images and registries.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/google/go-containerregistry/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: f43fe0dc9830a493d5af9dfdffbdd6910a5bf55f5fd493adcc59bd4da857d5bf

  - uses: go/bump
    with:
      deps: github.com/docker/distribution@v2.8.2 github.com/docker/docker@v24.0.7

  - uses: go/build
    with:
      packages: ./cmd/crane
      ldflags: -s -w -buildid= -X github.com/google/go-containerregistry/cmd/crane/cmd.Version=${{package.version}} -X github.com/google/go-containerregistry/pkg/v1/remote/transport.Version=${{package.version}}
      output: crane

  - uses: strip

update:
  enabled: true
  github:
    identifier: google/go-containerregistry
    strip-prefix: v
