package:
  name: dagdotdev
  version: 0.0.3
  epoch: 0
  description: oci and apk explorer
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4aa2a5c7af0bde3a3c826977404f88d803588972
      repository: https://github.com/jonjohnsonjr/dagdotdev
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: dagdotdev

  - uses: strip

update:
  enabled: true
  github:
    identifier: jonjohnsonjr/dagdotdev
    strip-prefix: v
