package:
  name: dask-gateway
  version: 2024.1.0
  epoch: 0
  description: "A multi-tenant server for securely deploying and managing Dask clusters."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - py3-aiohttp
      - py3-build
      - py3-colorlog
      - py3-cryptography
      - py3-gpep517
      - py3-installer
      - py3-pip
      - py3-setuptools
      - py3-traitlets
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dask/dask-gateway
      tag: ${{package.version}}
      expected-commit: 52a523041a509dd4aae3ff831cc09dbaf95bd32c

  - runs: |
      cd dask-gateway
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1

      python3 -m installer -d "${{targets.destdir}}" dist/dask_gateway*.whl

subpackages:
  - name: dask-gateway-server
    description: A multi-tenant server for securely deploying and managing Dask clusters
    pipeline:
      - name: Python Build
        runs: |
          cd dask-gateway-server
          python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          install -Dm755 ./dask_gateway_server/proxy/dask-gateway-proxy "${{targets.subpkgdir}}/usr/bin/"
          python -m installer -d "${{targets.subpkgdir}}/" dist/dask_gateway_server*.whl
    dependencies:
      runtime:
        - py3-sqlalchemy
        - py3-typing-extensions
        - py3-traitlets
        - py3-colorlog
        - py3-aiohttp
        - py3-cryptography
        - py3-kubernetes-asyncio

update:
  enabled: true
  github:
    identifier: dask/dask-gateway
    use-tag: true
