package:
  name: datadog-security-agent-policies
  version: 0.55.1
  epoch: 0
  description: "Policies for Security Agent - compliance and runtime checks"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/DataDog/security-agent-policies
      tag: v${{package.version}}
      expected-commit: b5d6e3ddb2e2585f12c4163f03c8623fe8a51476

  - runs: |
      mkdir -p ${{targets.destdir}}/etc/datadog-agent/compliance.d
      cp compliance/containers/* ${{targets.destdir}}/etc/datadog-agent/compliance.d

update:
  enabled: true
  github:
    identifier: DataDog/security-agent-policies
    use-tag: true
    strip-prefix: v
