package:
  name: datadog-agent
  version: 7.50.3
  epoch: 0
  description: "Collect events and metrics from your hosts that send data to Datadog."
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - coreutils
      - gcc-12
      - go-1.21
      - py3-boto3
      - py3-codeowners
      - py3-docker
      - py3-docker-squash
      - py3-dulwich
      - py3-invoke
      - py3-packaging
      - py3-pip
      - py3-reno
      - py3-requests
      - py3-toml
      - py3-urllib3
      - py3-wheel
      - python-3
      - python-3-dev
  environment:
    # CGo allows Go programs to call C code
    CGO_ENABLED: "1"
    # -Os optimizes the code for size
    # -I/build/datadog-agent/dev/include adds the directory to search
    CGO_CFLAGS: "-Os -I${{targets.destdir}}/home/build/dev/include/"
    # Pass options to the linker. -L/build/datadog-agent/dev/lib adds directory to search for libraries
    CGO_LDFLAGS: "-L${{targets.destdir}}/home/build/dev/lib/"
    # disables generation of debugging information
    # omits the symbol table and debug information, further reducing the size of the binary.
    GOFLAGS: "-ldflags=-w -ldflags=-s"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/DataDog/datadog-agent
      tag: ${{package.version}}
      expected-commit: abce0cb22b94b1519861b36ac9b8c9ea317bf6a1

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11 github.com/go-git/go-git/v5@v5.11.0
      replaces: github.com/cloudflare/circl=github.com/cloudflare/circl@v1.3.7
      go-version: "1.21.0"

  - runs: |
      export PATH=$PATH:$GOPATH/bin
      mkdir -p "$GOPATH/src/github.com/DataDog/"
      ln -sf /home/build/ "$GOPATH"/src/github.com/DataDog/datadog-agent
      go mod tidy

      invoke deps
      invoke install-tools

      invoke rtloader.make \
        --python-runtimes=3 \
        --cmake-options="\
          -DCMAKE_INSTALL_LIBDIR=lib \
          -DCMAKE_CXX_FLAGS=-Os \
          -DCMAKE_C_FLAGS=-Os" \
      && invoke rtloader.install

      invoke agent.build --build-exclude=systemd --python-runtimes 3

      mkdir -p \
        ${{targets.destdir}}/usr/lib/include \
        && cp /home/build/dev/lib/* ${{targets.destdir}}/usr/lib/ \
        && cp /home/build/dev/include/* ${{targets.destdir}}/usr/lib/include/ \

      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib

      mkdir -p \
        ${{targets.destdir}}/opt/datadog-agent/bin/agent/dist \
        ${{targets.destdir}}/opt/datadog-agent/run \
        ${{targets.destdir}}/etc/datadog-agent \
      && touch ${{targets.destdir}}/opt/datadog-agent/requirements-agent-release.txt \
      && touch ${{targets.destdir}}/opt/datadog-agent/final_constraints-py3.txt

      cp bin/agent/agent ${{targets.destdir}}/opt/datadog-agent/bin/agent/agent

      cp -r \
        bin/agent/dist/checks \
        bin/agent/dist/config.py \
        bin/agent/dist/utils \
        bin/agent/dist/views \
        ${{targets.destdir}}/opt/datadog-agent/bin/agent/dist/

      cp -r bin/agent/dist/conf.d ${{targets.destdir}}/etc/datadog-agent/conf.d/

      mkdir -p ${{targets.destdir}}/etc/datadog-agent/ && cp \
        Dockerfiles/agent/datadog-docker.yaml \
        Dockerfiles/agent/datadog-ecs.yaml \
        bin/agent/dist/system-probe.yaml \
        ${{targets.destdir}}/etc/datadog-agent/

      cp \
        bin/agent/dist/datadog.yaml \
        ${{targets.destdir}}/etc/datadog-agent/datadog.yaml.example

update:
  enabled: true
  github:
    identifier: DataDog/datadog-agent
  ignore-regex-patterns:
    - 'lambda-extension.*'
