#nolint:valid-pipeline-git-checkout-commit,valid-pipeline-git-checkout-tag
package:
  name: ddp-tool
  version: 1.0.34.0_git20241031
  epoch: 0
  description: Intel Dynamic Device Personalization Tool
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - gcc
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3868a732013b8e8817f6453b58a170f669d99a68
      repository: https://github.com/intel/ddp-tool/
      branch: master

  - runs: |
      export CFLAGS=${CFLAGS/-Wp,-D_FORTIFY_SOURCE=3/}
      export CPPFLAGS="$CFLAGS"
      export CXXFLAGS="$CFLAGS"
      mkdir -p "${{targets.contextdir}}"/usr/bin
      make ddptool
      install -Dm755 ddptool "${{targets.contextdir}}"/usr/bin/ddptool

  - uses: strip

update:
  enabled: true
  git: {}
  schedule:
    period: daily
    reason: Upstream does not maintain tags or releases

test:
  pipeline:
    - runs: |
        ddptool -j | grep "No driver available"
