package:
  name: docker-cli-buildx
  version: 0.18.0
  epoch: 0
  description: buildx is a Docker CLI plugin for extended build capabilities with BuildKit.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/buildx
      tag: v${{package.version}}
      expected-commit: fa4461b9a1ec45c23d1b9e32dee0d0a8ed29900b

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/libexec/docker/cli-plugins/
      make build
      chmod +x bin/build/docker-buildx
      cp bin/build/docker-buildx ${{targets.destdir}}/usr/libexec/docker/cli-plugins/

update:
  enabled: true
  github:
    identifier: docker/buildx
    strip-prefix: v
    tag-filter: v
