package:
  name: eksctl
  version: 0.181.0
  epoch: 1
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaveworks/eksctl
      expected-commit: 48a8e87dede5c400bf9cdd204c7a9ded0b279ae7
      tag: v${{package.version}}

  - runs: |
      make binary
      mkdir -p ${{targets.destdir}}/usr/bin
      mv eksctl ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: weaveworks/eksctl
    strip-prefix: v
