package:
  name: eksctl
  version: 0.182.0
  epoch: 0
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaveworks/eksctl
      expected-commit: 40a6990a0f86086897c7a660a95de2b55f8dc1da
      tag: v${{package.version}}

  - runs: |
      make binary
      mkdir -p ${{targets.destdir}}/usr/bin
      mv eksctl ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: weaveworks/eksctl
    strip-prefix: v
