package:
  name: esbuild
  version: 0.21.5
  epoch: 0
  description: An extremely fast bundler for the web
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/evanw/esbuild
      tag: v${{package.version}}
      expected-commit: fc37c2fa9de2ad77476a6d4a8f1516196b90187e

  - runs: |
      node scripts/esbuild.js --update-version-go

  - uses: go/build
    with:
      packages: ./cmd/esbuild
      output: esbuild

update:
  enabled: true
  github:
    identifier: evanw/esbuild
    strip-prefix: v
