package:
  name: esbuild
  version: 0.21.4
  epoch: 2
  description: An extremely fast bundler for the web
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/evanw/esbuild
      tag: v${{package.version}}
      expected-commit: 67cbf87a4909d87a902ca8c3b69ab5330defab0a

  - runs: |
      node scripts/esbuild.js --update-version-go

  - uses: go/build
    with:
      packages: ./cmd/esbuild
      output: esbuild

update:
  enabled: true
  github:
    identifier: evanw/esbuild
    strip-prefix: v
