package:
  name: execline
  version: 2.9.6.0
  epoch: 0
  description: "a small scripting language intended to be an alternative to shell scripting"
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - skalibs-dev
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://skarnet.org/software/execline/execline-${{package.version}}.tar.gz
      expected-sha256: ba2a27e97c5eb6bd7ca6a0987a8925e44465a5be996daa0d18f8feca37d7571a

  - name: Configure
    runs: |
      ./configure \
        --enable-shared \
        --enable-static \
        --disable-allstatic \
        --libdir=/usr/lib \
        --with-dynlib=/lib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "execline-dev"
    description: "execline development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 5482
