package:
  name: frp
  version: 0.58.1
  epoch: 1
  description: A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e64969221784b97338e821f6f5606cfaa40177c5
      repository: https://github.com/fatedier/frp
      tag: v${{package.version}}

  - runs: |
      make
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/frp* ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: fatedier/frp
    strip-prefix: v
