package:
  name: fzf
  version: 0.52.1
  epoch: 0
  description: A command-line fuzzy finder
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com//junegunn/fzf
      tag: ${{package.version}}
      expected-commit: 6432f00f0d026c61f683c83ded4d2e15317e927e

  - uses: go/build
    with:
      packages: .
      output: fzf
      ldflags: -s -w  -X main.version=v${{ package.version }} -X main.revision=$(git rev-parse --short HEAD)

  - uses: strip

update:
  enabled: true
  github:
    identifier: junegunn/fzf
    use-tag: true
