package:
  name: gh
  version: 2.42.1
  epoch: 0
  description: GitHub's official command line tool
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 57f6787c154d56d3c5461afed619e36b8a8394ec
      repository: https://github.com/cli/cli
      tag: v${{package.version}}

  - runs: make install prefix=${{targets.destdir}}/usr

  - uses: strip

update:
  enabled: true
  github:
    identifier: cli/cli
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        gh --version
