package:
  name: gobump
  version: 0.7.0
  epoch: 0
  description: Go tool to declaratively bump dependencies
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/gobump.git
      tag: v${{package.version}}
      expected-commit: b10c54a40ba783d7dd7aec4127dc809b22d7f3d3

  - uses: go/build
    with:
      packages: .
      output: gobump

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/gobump
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        gobump version
