package:
  name: gomplate
  version: 3.11.8
  epoch: 1
  description: A go templating utility.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f525a6eaec343d0d8f576195b63ed3ea63d69143
      repository: https://github.com/hairyhenderson/gomplate
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/golang/protobuf@v1.5.4
      replaces: github.com/cloudflare/circl=github.com/cloudflare/circl@v1.3.7

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -o ${{targets.destdir}}/usr/bin \
        -ldflags "-w -s -X github.com/hairyhenderson/gomplate/v3/version.Version=${{package.version}} \
        -X github.com/hairyhenderson/gomplate/v3/version.GitCommit=$(git rev-parse --short HEAD)" \
        github.com/hairyhenderson/gomplate/v3/cmd/gomplate

      # Test that the binary can be run, since there have been issues with the
      # Go version used by the tool that only manifest at runtime.
      ${{targets.destdir}}/usr/bin/gomplate -i 'the answer is: {{ mul 6 7 }}'

update:
  enabled: true
  github:
    identifier: hairyhenderson/gomplate
    strip-prefix: v
