package:
  name: grype
  version: 0.74.0
  epoch: 3
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: a808408584c0532f50095832438e97debe1c11aa

  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7
      go-version: "1.21.0"

  - uses: go/build
    with:
      ldflags: -w -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        grype --version
