package:
  name: grype
  version: 0.74.2
  epoch: 0
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: 90fa3f29fa6deb392ea8a2b6cad144fb3c9edef3

  - uses: go/build
    with:
      ldflags: -w -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        grype --version
