package:
  name: helm
  version: 3.14.0
  epoch: 0
  description: The Kubernetes Package Manager
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helm/helm
      tag: v${{package.version}}
      expected-commit: 3fc9f4b2638e76f26739cd77c7017139be81d0ea

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11

  - runs: |
      make build
      install -Dm755 ./bin/helm "${{targets.destdir}}/usr/bin/helm"

  - uses: strip

update:
  enabled: true
  github:
    identifier: helm/helm
    strip-prefix: v
