package:
  name: hugo
  version: 0.127.0
  epoch: 0
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: 74e0f3bd63c51f3c7a0f07a7c779eec9e922957e

  - uses: go/build
    with:
      packages: .
      output: hugo

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v
