package:
  name: ipfs
  version: 0.26.0
  epoch: 0
  description: An IPFS implementation in Go
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubo

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - fuse3
      - go-1.20
      - openssl # significantly reduces background CPU usage, but requires CGO and gcc

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 096f510ab206c119693f145bc3331eeb33a69e07
      repository: https://github.com/ipfs/kubo
      tag: v${{package.version}}

  - runs: |
      CGO_ENABLED=1 GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) GOFLAGS=-buildvcs=false make build GOTAGS=openssl
      install -m755 -D ./cmd/ipfs/ipfs "${{targets.destdir}}"/usr/bin/ipfs

  - runs: |
      # create fs-repo directory
      mkdir -p /data/ipfs
      # create mount points
      mkdir /ipfs /ipns

  - uses: strip

update:
  enabled: true
  github:
    identifier: ipfs/kubo
    strip-prefix: v
