package:
  name: iproute2
  version: 6.9.0
  epoch: 0
  description: IP Routing Utilities
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - bash
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - elfutils-dev
      - flex
      - iptables-dev

pipeline:
  - uses: fetch
    with:
      uri: https://kernel.org/pub/linux/utils/net/iproute2/iproute2-${{package.version}}.tar.xz
      expected-sha256: 2f643d09ea11a4a2a043c92e2b469b5f73228cbf241ae806760296ed0ec413d0

  - uses: autoconf/configure
    with:
      opts: |
        --build=${{host.triplet.gnu}} \
        --host=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var

  - uses: autoconf/make
    with:
      opts: |
        CCOPTS="-D_GNU_SOURCE $CFLAGS" LIBDIR=/lib

  - uses: autoconf/make-install

subpackages:
  - name: iproute2-doc
    description: iproute2 documentation
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 1392
