package:
  name: ipset
  version: "7.22"
  epoch: 0
  description: Manage Linux IP sets
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmnl-dev
      - libtool
      - linux-headers

pipeline:
  - uses: fetch
    with:
      uri: https://ipset.netfilter.org/ipset-${{package.version}}.tar.bz2
      expected-sha512: e375a9110eb7974480147c57eb2cff4bdd03c7704cdae006a3d254cc80fada587aa8aee25a86f7cab29db83f5e283c5f9a47a314297317660ebba5097f623d79

  - uses: autoconf/configure
    with:
      opts: |
        --build=${{host.triplet.gnu}} \
        --host=${{host.triplet.gnu}} \
        --with-kmod=no \
        --prefix=/usr

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ipset-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ipset
    description: ipset dev

  - name: ipset-doc
    pipeline:
      - uses: split/manpages
    description: ipset manpages

update:
  enabled: true
  release-monitor:
    identifier: 1393
