package:
  name: iputils
  version: "20240117"
  epoch: 0
  description: IP Configuration Utilities
  copyright:
    - license: BSD-3-Clause AND GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-dev
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha512: 1755de6adb509418507c3f10521715ff3bf7ba38d3bbd9a102a48ae0a9f88fcb1f457bcb38624dce2281912e0e0ffc3fbf74e0e618ed2d21014710e967c7dad3
      uri: https://github.com/iputils/iputils/archive/${{package.version}}.tar.gz

  - runs: |
      meson \
           -Db_lto=true \
           -DNO_SETCAP_OR_SUID=true \
           -DBUILD_MANS=false \
           -DUSE_IDN=false \
           -DUSE_GETTEXT=false \
           . output

  - uses: meson/compile

  - uses: meson/install

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/sbin
      mkdir -p "${{targets.destdir}}"/bin
      mv ./output/ping/ping "${{targets.destdir}}"/bin/ping
      for name in arping clockdiff tracepath; do
         install -Dm755 output/$name "${{targets.destdir}}"/usr/sbin/$name
      done
      ln -s "${{targets.destdir}}"/usr/sbin/tracepath "${{targets.destdir}}"/usr/sbin/tracepath6
      ln -s "${{targets.destdir}}"/bin/ping "${{targets.destdir}}"/bin/ping6

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 1395
