package:
  name: istio-pilot-agent-1.20
  version: 1.20.2
  epoch: 1
  description: Nanny binary for Istio Envoy
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-pilot-agent=1.20

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 5f5d657c72d30a97cae97938de3a6831583e9f15

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0
      go-version: "1.21"

  - uses: go/build
    with:
      packages: ./pilot/cmd/pilot-agent
      output: pilot-agent
      # istio default ldflags: https://github.com/istio/istio/blob/master/Makefile.core.mk#L210
      ldflags: "-extldflags -static -s -w"
      # istio default agent tags: https://github.com/istio/istio/blob/master/Makefile.core.mk#L239
      tags: "agent,disable_pgv"

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio/envoy
      cp ./tools/packaging/common/envoy_bootstrap.json \
        ${{targets.destdir}}/var/lib/istio/envoy/envoy_bootstrap_tmpl.json
      cp ./tools/packaging/common/gcp_envoy_bootstrap.json \
        ${{targets.destdir}}/var/lib/istio/envoy/gcp_envoy_bootstrap_tmpl.json

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # link /usr/local/bin/pilot-agent -> /usr/bin/pilot-agent to match
          # what the Istio Helm charts may expect.
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/pilot-agent ${{targets.subpkgdir}}/usr/local/bin/pilot-agent
    dependencies:
      provides:
        - istio-pilot-agent-compat=1.20.999

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.20.
    use-tag: true
