package:
  name: jellyfin-web
  version: 10.9.4
  epoch: 0
  description: Web Client for Jellyfin
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - jellyfin
      - nodejs

environment:
  contents:
    packages:
      - busybox
      - jellyfin
      - nodejs
      - npm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jellyfin/jellyfin-web
      tag: v${{package.version}}
      expected-commit: d9c54408644c6cf0a3d50f4ad6e823b6dfffa82f

  - runs: |
      npm ci --no-audit --unsafe-perm
      npm run build:production

      mkdir -p "${{targets.destdir}}"/usr/lib/jellyfin/jellyfin-web
      cp -r dist/* "${{targets.destdir}}"/usr/lib/jellyfin/jellyfin-web

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '.*alpha.*'
    - '.*beta.*'
    - '.*rc.*'
  github:
    identifier: jellyfin/jellyfin-web
    use-tag: true
    strip-prefix: v
