package:
  name: jupyterhub-k8s-hub
  version: 3.3.7
  epoch: 1
  description: Zero to JupyterHub with Kubernetes
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - configurable-http-proxy
      - iptables
      - py3-jupyterhub
      - py3-jupyterhub-firstuseauthenticator
      - py3-jupyterhub-hmacauthenticator
      - py3-jupyterhub-idle-culler
      - py3-jupyterhub-kubespawner
      - py3-jupyterhub-ldapauthenticator
      - py3-jupyterhub-ltiauthenticator
      - py3-jupyterhub-nativeauthenticator
      - py3-jupyterhub-tmpauthenticator
      - py3-kubernetes-asyncio
      - py3-mwoauth
      - py3-nullauthenticator
      - py3-oauthenticator
      - py3-psycopg2
      - py3-pycurl
      - py3-pyjwt
      - py3-pymysql
      - py3-python-dateutil
      - py3-sqlalchemy-cockroachdb
      - py3-statsd
      - py3-tornado
      - python3
      - tini

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jupyterhub/zero-to-jupyterhub-k8s
      tag: ${{package.version}}
      expected-commit: 71ecf69f2f04ae5426ab7602c2844499b36bfc66

  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/jupyterhub
      cp -r jupyterhub/files/hub/* "${{targets.destdir}}"/etc/jupyterhub/

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by jupyterhub-k8s-hub"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/etc/jupyterhub
          ln -sf /etc/jupyterhub/jupyterhub_config.py ${{targets.subpkgdir}}/usr/local/etc/jupyterhub/jupyterhub_config.py
          ln -sf /etc/jupyterhub/z2jh.py ${{targets.subpkgdir}}/usr/local/etc/jupyterhub/z2jh.py
    dependencies:
      runtime:
        - jupyterhub-k8s-hub

update:
  enabled: true
  github:
    identifier: jupyterhub/zero-to-jupyterhub-k8s

test:
  environment:
    contents:
      packages:
        - openssl # Fixes: RuntimeError: OpenSSL 3.0's legacy provider failed to load.
        - curl
  pipeline:
    - runs: |
        nohup /usr/bin/jupyterhub > $bin.out 2> $bin.err < /dev/null &
        pid=$!
        sleep 3

        if ! (cat $bin.out $bin.err | grep -i "JupyterHub is now running"); then
          echo "Could not find expected 'JupyterHub is now running' log message in the output!"
          cat $bin.out
          cat $bin.err
          exit 1
        fi

        curl http://localhost:8000/_chp_healthz | grep -qi "OK"

        echo "Stopping..."
        kill $pid
        sleep 3
