package:
  name: just
  version: 1.28.0
  epoch: 0
  description: "just is a handy way to save and run project-specific commands."
  copyright:
    - license: CC0-1.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/casey/just
      expected-commit: 3ddd1b168308db2b88daac9ea70a3b63629ef034
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/just ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: casey/just
