package:
  name: kafka-proxy
  version: 0.3.10
  epoch: 0
  description: Allows a service to connect to Kafka brokers without having to deal with SASL/PLAIN authentication and SSL certificates
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grepplabs/kafka-proxy
      tag: v${{package.version}}
      expected-commit: d7bec2f42c8deb3087c390d2e345f6f7605a5c9a

  - uses: go/build
    with:
      packages: .
      output: kafka-proxy

  - uses: strip

update:
  enabled: true
  github:
    identifier: grepplabs/kafka-proxy
    strip-prefix: v

test:
  pipeline:
    - runs: |
        kafka-proxy --help
