package:
  name: kdash
  version: 0.5.0
  epoch: 0
  description: "A simple and fast dashboard for Kubernetes"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgit2-dev
      - libxcb
      - libxcb-dev
      - openssl
      - openssl-dev
      - pkgconf
      - pkgconf-dev
      - python3
      - rust
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kdash-rs/kdash
      tag: v${{package.version}}
      expected-commit: c6e4cb672cef0e88bb96703f92bfeb9fb78f3f80

  - runs: |
      OPENSSL_NO_VENDOR=true cargo build --release
      install -Dm755 target/release/kdash "${{targets.destdir}}"/usr/bin/kdash

  - uses: strip

update:
  enabled: true
  github:
    identifier: kdash-rs/kdash
    strip-prefix: v
