package:
  name: kor
  version: 0.4.2
  epoch: 0
  description: A Golang Tool to discover unused Kubernetes Resources
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yonahd/kor
      tag: v${{package.version}}
      expected-commit: 2fdeab299d60a277b455a6ccf162fff0f3ba616b

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: kor

  - uses: strip

update:
  enabled: true
  github:
    identifier: yonahd/kor
    strip-prefix: v
