package:
  name: kots
  version: 1.105.4
  epoch: 0
  description: Kubernetes Off-The-Shelf (KOTS) Software
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - nodejs
      - yarn

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/replicatedhq/kots/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: ea7cd49e176523f254a01586fb837f87cec825df63cb78b6bc334b495f614af1

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11 github.com/go-git/go-git/v5@v5.11.0
      go-version: "1.21.0"

  - runs: |
      set -x
      mkdir -p ${{targets.destdir}}/etc
      mkdir -p ${{targets.destdir}}/usr/bin

      # Scripts etc.
      mv deploy/assets/* "${{targets.destdir}}/etc/"

      # kotsadm and kots binaries
      export VERSION=${{package.version}}
      export GIT_TAG=${{package.version}}

      # Set environment variables from repository
      source .image.env

      KOTS_KUSTOMIZE_BIN_DIR=/usr/bin

      # TODO: fix pact build error on arm https://github.com/pact-foundation/pact-js-core/issues/264
      export PACT_SKIP_BINARY_INSTALL=true

      # Configure Yarn
      yarn install --pure-lockfile --network-concurrency 1

      # removing tests for now to see if this builds
      make -C web deps lint build-kotsadm
      make vet kots build

      mv bin/kotsadm "${{targets.destdir}}/usr/bin/"
      mv bin/kots "${{targets.destdir}}/usr/bin/"

subpackages:
  - name: kots-symlink-compat # inconsistent naming for compat however this package name already exists
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin

          ln -s /usr/bin ${{targets.subpkgdir}}/usr/local/bin
          ln -s /usr/bin/kotsadm ${{targets.subpkgdir}}/kotsadm
          ln -s /usr/bin/kots ${{targets.subpkgdir}}/kots

          # loop over all the assets in /etc and symlink them into the root subpackage
          for file in ${{targets.destdir}}/etc/*; do
              filename=$(basename $file)
              ln -s /etc/$filename ${{targets.subpkgdir}}/$filename
          done

          # TODO: this is a manual intervention whenever helm bumps its major version
          ln -s /usr/bin/helm ${{targets.subpkgdir}}/usr/local/bin/helm
          ln -s /usr/bin/helm ${{targets.subpkgdir}}/usr/local/bin/helm3

          # TODO: this is a manual intervention whenever kustomize bumps its major version
          ln -s /usr/bin/kustomize ${{targets.subpkgdir}}/usr/local/bin/kustomize
          ln -s /usr/bin/kustomize ${{targets.subpkgdir}}/usr/local/bin/kustomize5

          ln -s /usr/bin/kubectl ${{targets.subpkgdir}}/usr/local/bin/kubectl
    description: Compatability package for kots

update:
  enabled: true
  github:
    identifier: replicatedhq/kots
    strip-prefix: v
