package:
  name: kustomize
  version: 5.4.2
  epoch: 2
  description: Customization of kubernetes YAML configurations
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/kustomize
      tag: kustomize/v${{package.version}}
      expected-commit: f309dfc54a4143225dd8af693a11703cc9e7d959

  - uses: go/build
    with:
      packages: ./kustomize
      output: kustomize
      ldflags: -X sigs.k8s.io/kustomize/api/provenance.version=kustomize/${{package.version}} -X 'sigs.k8s.io/kustomize/api/provenance.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/kustomize
    strip-prefix: kustomize/v
    tag-filter: kustomize/v
    use-tag: true
