package:
  name: kyverno
  version: 1.12.3
  epoch: 1
  description: Kubernetes Native Policy Management
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 46293db866d6b741c109f8eeba202b5aa4c191b6
      repository: https://github.com/kyverno/kyverno
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0

  - runs: |
      make build-all
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 cmd/kyverno/kyverno ${{targets.destdir}}/usr/bin/kyverno

  - uses: strip

subpackages:
  - name: kyverno-init-container
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/kyverno-init/kyvernopre ${{targets.subpkgdir}}/usr/bin/kyvernopre

  - name: kyverno-reports-controller
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/reports-controller/reports-controller ${{targets.subpkgdir}}/usr/bin/reports-controller

  - name: kyverno-background-controller
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/background-controller/background-controller ${{targets.subpkgdir}}/usr/bin/background-controller

  - name: kyverno-cleanup-controller
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/cleanup-controller/cleanup-controller ${{targets.subpkgdir}}/usr/bin/cleanup-controller

  - name: kyverno-cli
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/cli/kubectl-kyverno/kubectl-kyverno ${{targets.subpkgdir}}/usr/bin/kubectl-kyverno

update:
  enabled: true
  ignore-regex-patterns:
    - '-beta'
    - '-rc'
  github:
    identifier: kyverno/kyverno
    strip-prefix: v
