package:
  name: libbpf
  version: 1.4.2
  epoch: 0
  description: "A library for interacting with the Linux kernel's Berkeley Packet Filter (BPF) facility from user space"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - elfutils-dev
      - linux-headers
      - wolfi-base
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libbpf/libbpf
      tag: v${{package.version}}
      expected-commit: 1b357586a7a62db7fe27af4ebe4bdefe6986cfd6

  - uses: autoconf/make
    with:
      dir: src

  - uses: autoconf/make-install
    with:
      dir: src

  - runs: |
      # poor mans consolidation of the libs into /usr/lib64
      mv "${{targets.destdir}}"/usr/lib64 "${{targets.destdir}}"/usr/lib
      mv "${{targets.destdir}}"/usr/lib "${{targets.destdir}}"/usr/lib64

  - uses: strip

subpackages:
  - name: libbpf-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libbpf

update:
  enabled: true
  github:
    identifier: libbpf/libbpf
    strip-prefix: v
