package:
  name: libcap-ng
  version: 0.8.5
  epoch: 0
  description: POSIX capabilities library
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3ba5294d1cbdfa98afaacfbc00b6af9ed2b83e8a21817185dfd844cc8c7ac6ff
      uri: https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --mandir=/usr/share/man \
            --infodir=/usr/share/info \
            --without-python \
            --without-python3 \
            --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - range: ""
    name: libcap-ng-static
    pipeline:
      - uses: split/static
    description: libcap-ng static

  - range: ""
    name: libcap-ng-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libcap-ng
        - linux-headers
    description: libcap-ng dev

  - range: ""
    name: libcap-ng-doc
    pipeline:
      - uses: split/manpages
    description: libcap-ng manpages

  - range: ""
    name: libcap-ng-utils
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/bin
    description: posix capabilities utils

update:
  enabled: true
  release-monitor:
    identifier: 1570
