package:
  name: libeconf
  version: 0.7.1
  epoch: 0
  description: Enhanced Config File Parser
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ccaf9121a8d15a043509af6e6545925b7e82a270
      repository: https://github.com/openSUSE/libeconf
      tag: v${{package.version}}

  - runs: meson build

  - runs: ninja -C build

  - runs: DESTDIR="${{targets.destdir}}" ninja -C build install

subpackages:
  - range: ""
    name: libeconf-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libeconf
    description: libeconf dev

update:
  enabled: true
  github:
    identifier: openSUSE/libeconf
    strip-prefix: v
