package:
  name: libhtp
  version: 0.5.48
  epoch: 1
  description: LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - glibc-iconv
      - libtool
      - m4
      - xz-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6a7378c7942592bfc662e0fcf34b560abd3f3704
      repository: https://github.com/OISF/libhtp
      tag: ${{package.version}}

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libhtp-static
    pipeline:
      - uses: split/static
    description: libhtp static

  - name: libhtp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libhtp
    description: libhtp dev

  - name: libhtp-doc
    pipeline:
      - uses: split/manpages
    description: libhtp manpages

update:
  enabled: true
  github:
    identifier: OISF/libhtp
    use-tag: true
