package:
  name: libidn2
  version: 2.3.4
  epoch: 1
  description: Encode/Decode library for internationalized domain names
  copyright:
    - license: GPL-2.0-or-later AND LGPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libunistring-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 93caba72b4e051d1f8d4f5a076ab63c99b77faee019b72b9783b267986dbb45f
      uri: https://ftp.gnu.org/gnu/libidn/libidn2-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --disable-nls

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: idn2-utils
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: libidn2  (CLI utilities)

  - name: libidn2-static
    pipeline:
      - uses: split/static
    description: libidn2 static

  - name: libidn2-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libidn2
    description: libidn2 dev

  - name: libidn2-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: libidn2 manpages

update:
  enabled: true
  release-monitor:
    identifier: 5597
