package:
  name: libkcapi
  version: 1.5.0
  epoch: 0
  description: Linux Kernel Crypto API User Space Interface Library
  copyright:
    - license: BSD-3-Clause OR GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - patch

pipeline:
  - uses: fetch
    with:
      expected-sha256: 15b550c14165a266fa233b485d029d54508da593dfa6d1731ec5d5a285c716e9
      uri: https://www.chronox.de/libkcapi/libkcapi-${{package.version}}.tar.xz

  - uses: patch
    with:
      patches: makefile.patch

  - runs: autoreconf -fvi

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --enable-kcapi-hasher \
        --enable-kcapi-speed \
        --enable-kcapi-rngapp \
        --enable-kcapi-encapp \
        --enable-kcapi-dgstapp \
        --enable-kcapi-test \
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      rm -r ${{targets.destdir}}/usr/libexec/

  - uses: strip

subpackages:
  - name: libkcapi-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libkcapi
    description: libkcapi dev

  - name: libkcapi-tools
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: libkcapi (commandline utilities)

  - name: libkcapi-doc
    pipeline:
      - uses: split/manpages
    description: libkcapi manpages

update:
  enabled: true
  release-monitor:
    identifier: 16828
