package:
  name: libmicrohttpd
  version: 0.9.77
  epoch: 0
  description: small C library that is supposed to make it easy to run an HTTP server as part of another application
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gnutls-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9e7023a151120060d2806a6ea4c13ca9933ece4eacfc5c9464d20edddb76b0a0
      uri: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --disable-thread-names \
        --enable-largefile \
        --enable-curl \
        --enable-https \
        --enable-messages

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libmicrohttpd-static
    pipeline:
      - uses: split/static
    description: libmicrohttpd static

  - name: libmicrohttpd-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmicrohttpd
    description: libmicrohttpd dev

  - name: libmicrohttpd-doc
    pipeline:
      - uses: split/manpages
    description: libmicrohttpd manpages

update:
  enabled: true
  release-monitor:
    identifier: 1658
