package:
  name: liboping
  version: 1.10.0
  epoch: 0
  description: A C library to generate ICMP echo requests
  copyright:
    - license: LGPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: eb38aa93f93e8ab282d97e2582fbaea88b3f889a08cbc9dbf20059c3779d5cd8
      uri: http://verplant.org/liboping/files/liboping-${{package.version}}.tar.bz2

  - runs: |
      CFLAGS="$CFLAGS -Wno-error" ./configure \
      	--prefix=/usr \
      	--libdir=/usr/lib \
      	--without-perl-bindings \
      	--disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: liboping-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - liboping
    description: liboping dev

  - name: liboping-doc
    pipeline:
      - uses: split/manpages
    description: liboping manpages

update:
  enabled: true
  release-monitor:
    identifier: 1695
