package:
  name: libpng
  version: 1.6.40
  epoch: 1
  description: Portable Network Graphics library
  copyright:
    - license: Libpng

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gawk
      - libtool
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8f720b363aa08683c9bf2a563236f45313af2c55d542b5481ae17dd8d183bb42
      uri: https://downloads.sourceforge.net/libpng/libpng-${{package.version}}.tar.gz

  - runs: autoreconf -vif

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libpng-doc
    pipeline:
      - uses: split/manpages
    description: libpng manpages

  - name: libpng-static
    description: libpng static library
    pipeline:
      - uses: split/static

  - name: libpng-utils
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: libpng utils

  - name: libpng-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpng
    description: libpng dev

update:
  enabled: true
  release-monitor:
    identifier: 1705
