package:
  name: libpaper
  version: 2.1.3
  epoch: 0
  description: Library for handling paper characteristics
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: b798be7c52036e684a90a68f0be954f173fea87886f8a1d25c6514a279216f4a
      uri: https://github.com/rrthomas/libpaper/releases/download/v${{package.version}}/libpaper-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libpaper-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpaper
    description: libpaper dev

  - name: libpaper-doc
    pipeline:
      - uses: split/manpages
    description: libpaper manpages

update:
  enabled: true
  github:
    identifier: rrthomas/libpaper
    strip-prefix: v
