package:
  name: libtool
  version: 2.4.7
  epoch: 3
  description: "GNU libtool"
  copyright:
    - license: LGPL-2.0-or-later AND GPL-2.0-or-later
  dependencies:
    runtime:
      - libltdl

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - help2man
      - m4

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/libtool/libtool-${{package.version}}.tar.xz
      expected-sha256: 4f7f217f057ce655ff22559ad221a0fd8ef84ad1fc5fcb6990cecc333aa1635d

  - uses: patch
    with:
      patches: libtool-fix-cross-compile.patch

  - runs: |
      M4=/usr/bin/m4 ./configure \
        --prefix=/usr

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libtool-doc"
    description: "libtool documentation"
    pipeline:
      - uses: split/manpages

  - name: "libltdl"
    description: "GNU libtool dynamic module loader"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libltdl.so* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 1741

test:
  environment:
    contents:
      packages:
        - build-base
  pipeline:
    - name: Compile and Execute Test
      runs: |
        cat <<'EOF' > hello.c
        #include <stdio.h>
        int main() { puts("Hello, world!"); return 0; }
        EOF
        libtool --mode=compile --tag=CC gcc -c hello.c -o hello.o
        libtool --mode=link --tag=CC gcc hello.o -o hello
        ./hello | grep -q "Hello, world!"
