package:
  name: liburing
  version: 2.5
  epoch: 0
  description: Linux kernel io_uring access library.
  copyright:
    - license: MIT or LGPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - glibc-dev
      - linux-headers

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f4e42a515cd78c8c9cac2be14222834be5f8df2b
      repository: https://github.com/axboe/liburing.git
      tag: liburing-${{package.version}}

  - runs: |
      ./configure \
        --prefix=/usr \
        --use-libc \
        --libdir=/usr/lib \
        --mandir=/usr/share/man

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: liburing-ffi
    description: liburing shared library
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/lib"
          mv ${{targets.destdir}}/usr/lib/liburing-ffi.so.* ${{targets.subpkgdir}}/usr/lib/

  - name: liburing-dev
    description: liburing development headers
    pipeline:
      - uses: split/dev

  - name: liburing-doc
    description: liburing documentation
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: axboe/liburing
    strip-prefix: liburing-
    tag-filter: liburing-
    use-tag: true
