package:
  name: lighttpd
  version: 1.4.73
  epoch: 1
  description: Secure, fast, compliant and very flexible web-server
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - e2fsprogs
      - flex
      - libdbi-dev
      - libtool
      - libxml2-dev
      - linux-pam-dev
      - lua5.4-dev
      - m4
      - openldap-dev
      - openssl-dev
      - pcre-dev
      - pcre2-dev
      - pkgconf-dev
      - readline-dev
      - sqlite-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://download.lighttpd.net/lighttpd/releases-1.4.x/lighttpd-${{package.version}}.tar.xz
      expected-sha512: ee41a72b09614d630174ef832b08c050708f62c0b6299e82b0a5f91a63d62702d31237ae5bb1850f0160b94e36a66af38a2d7abdaa920235265d416d2b0b4015

  - runs: |
      ./autogen.sh
      mkdir -p "${{targets.destdir}}"/var/tmp

  - uses: autoconf/configure
    with:
      opts: |
        --with-ldap \
        --with-pam \
        --with-attr \
        --with-openssl \
        --with-webdav-props \
        --with-webdav-locks \
        --with-lua \
        --with-pcre2 \
        --with-brotli \
        --with-zstd \
        --with-dbi

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 1817
