package:
  name: llvm-lld-18
  version: 18.1.6
  epoch: 0
  description: The LLVM Linker
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - llvm-lld=18

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-18
      - cmake
      - curl
      - git
      - libedit-dev
      - llvm-18
      - llvm-18-dev
      - llvm-cmake-18
      - llvm-libunwind-dev
      - samurai
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - uses: fetch
    with:
      expected-sha256: f1f059c2bf98ffa558cd0c48ea568736c41f0c8029dabb53147d48b9efdaa802
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/lld-${{package.version}}.src.tar.xz

  - runs: |
      cmake -B build -G Ninja -Wno-dev \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_MODULE_PATH=/usr/lib/llvm-${{vars.major-version}}/share/cmake/Modules \
        -DLLVM_COMMON_CMAKE_UTILS="/usr/lib/llvm-${{vars.major-version}}/share/cmake" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DLLVM_INCLUDE_TESTS=OFF \
        -DLLD_BUILT_STANDALONE=ON \
        -DLLVM_CONFIG=/usr/lib/llvm-${{vars.major-version}}/bin/llvm-config \
        -DLLVM_INCLUDE_DIRS=/usr/lib/llvm-${{vars.major-version}}/include

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR=${{targets.destdir}} cmake --install build

subpackages:
  - name: llvm-lld-18-static
    pipeline:
      - uses: split/static

  - name: llvm-lld-18-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - llvm-lld-18
    description: llvm-lld dev

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    use-tag: true
    tag-filter: llvmorg-18.1.
    strip-prefix: llvmorg-
