package:
  name: local-path-provisioner
  version: 0.0.27
  epoch: 1
  description: Dynamically provisioning persistent local storage with Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/local-path-provisioner
      tag: v${{package.version}}
      expected-commit: 63feacb04e47fbc7285cc666ce3fbf6fdf2b7937

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      packages: .
      output: local-path-provisioner
      ldflags: -w -X main.VERSION=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: rancher/local-path-provisioner
    strip-prefix: v
