package:
  name: melange
  version: 0.8.3
  epoch: 2
  description: build APKs from source code
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bubblewrap
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c673c416e7a0b40086559bef8d0d4c77be01c834
      repository: https://github.com/chainguard-dev/melange
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: chainguard.dev/apko@v0.14.5

  - runs: |
      make melange
      install -m755 -D ./melange "${{targets.contextdir}}"/usr/bin/melange

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/melange
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - apk-tools
  pipeline:
    - runs: |
        apk del wolfi-base busybox
        melange version

        # busybox is needed for the build, but we want to demonstrate
        # that it's not needed at runtime.
        # TODO(jason): Can't currently test this due to container inception nonsense that's just too crazy to justify.
        # melange build example.yaml --arch=x86_64
