package:
  name: minify
  version: 2.20.31
  epoch: 0
  description: "Go minifiers for web formats"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdewolff/minify
      tag: v${{package.version}}
      expected-commit: 06a486e8ec3de053b99c178dd7309a1750f73352

  - uses: go/build
    with:
      packages: ./cmd/minify
      ldflags: -s -w
      output: minify

  - uses: strip

subpackages:
  - name: minify-bash-completion
    description: bash completion for minify
    pipeline:
      - runs: |
          _out="${{targets.subpkgdir}}"/usr/share/bash-completion/completions
          mkdir -p $_out
          install -Dm644 ./cmd/minify/bash_completion $_out
    dependencies:
      runtime:
        - minify

update:
  enabled: true
  github:
    identifier: tdewolff/minify
    strip-prefix: v
    tag-filter: v
