package:
  name: minify
  version: 2.20.33
  epoch: 0
  description: "Go minifiers for web formats"
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdewolff/minify
      tag: v${{package.version}}
      expected-commit: f75995ce528b50eef7e6b7885ae0a50d731898db

  - uses: go/build
    with:
      packages: ./cmd/minify
      output: minify

subpackages:
  - name: minify-bash-completion
    description: bash completion for minify
    pipeline:
      - runs: |
          _out="${{targets.subpkgdir}}"/usr/share/bash-completion/completions
          mkdir -p $_out
          install -Dm644 ./cmd/minify/bash_completion $_out

update:
  enabled: true
  github:
    identifier: tdewolff/minify
    strip-prefix: v
    tag-filter: v
