package:
  name: neuvector-agent
  version: 5.3.2
  epoch: 0
  description: "NeuVector Agent"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      expected-commit: edbdcba632835d56dcc92ba86323c8a196471289
      repository: https://github.com/neuvector/neuvector.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.3+incompatible github.com/containerd/containerd@v1.5.18 github.com/opencontainers/runc@v1.1.12 github.com/opencontainers/image-spec@v1.1.0 github.com/docker/distribution@v2.8.2-beta.1+incompatible golang.org/x/sys@v0.19.0 golang.org/x/net@v0.23.0 golang.org/x/text@v0.14.0 gopkg.in/yaml.v3@v3.0.1
      replaces: github.com/samalba/dockerclient=github.com/Dentrax/dockerclient@v0.1.0

  - runs: |
      sed -i 's|interim/master.xxxx|${{package.version}}|g' agent/version.go

  - uses: go/build
    with:
      modroot: agent
      ldflags: "-X main.version=${{package.version}} -s -w"
      packages: .
      output: agent
      prefix: usr/local

  - uses: go/build
    with:
      modroot: agent/workerlet/pathWalker
      ldflags: "-X main.version=${{package.version}} -s -w"
      packages: .
      output: pathWalker
      prefix: usr/local

  - runs: |
      chmod +x agent/nvbench/*.sh
      install -Dm755 agent/nvbench/*.sh ${{targets.contextdir}}/usr/local/bin/
      install -Dm755 agent/nvbench/*.rem ${{targets.contextdir}}/usr/local/bin/
      install -Dm755 agent/nvbench/*.tmpl ${{targets.contextdir}}/usr/local/bin/

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\-.*'
  github:
    identifier: neuvector/neuvector
    tag-filter: v
    strip-prefix: v

test:
  pipeline:
    - runs: |
        agent -v | grep "${{package.version}}"
