package:
  name: neuvector-controller
  version: 5.3.2
  epoch: 5
  description: NeuVector Full Lifecycle Container Security Platform.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - ca-certificates
      - consul
      - ethtool
      - iproute2
      - neuvector-monitor
      - neuvector-nstools
      - opa
      - pcre
      - procps

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - pcre-dev
      - pcre2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/neuvector
      tag: v${{package.version}}
      expected-commit: edbdcba632835d56dcc92ba86323c8a196471289

  - uses: go/bump
    with:
      how-diff: true
      deps: golang.org/x/net@v0.23.0 golang.org/x/crypto@v0.22.0 github.com/opencontainers/image-spec@v1.1.0 github.com/docker/distribution@v2.8.2-beta.1+incompatible github.com/opencontainers/runc@v1.1.12 github.com/containerd/containerd@v1.6.26 google.golang.org/grpc@v1.56.3 google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4 github.com/docker/docker@v26.1.0+incompatible
      replaces: github.com/samalba/dockerclient=github.com/Dentrax/dockerclient@v0.1.0 github.com/dgrijalva/jwt-go=github.com/golang-jwt/jwt/v4@v4.4.2

  - runs: |
      sed -i 's|interim/master.xxxx|${{package.version}}|g' controller/version.go

  - uses: go/build
    with:
      modroot: controller
      ldflags: "-X main.Version=${{package.version}} -X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"
      packages: .
      output: controller
      prefix: usr/local

  - runs: |
      # Create Folders
      mkdir -p ${{targets.contextdir}}/etc
      mkdir -p ${{targets.contextdir}}/usr/local/bin
      mkdir -p ${{targets.contextdir}}/etc/neuvector/templates

      # Scripts
      cp scripts/sysctl.conf ${{targets.contextdir}}/etc/
      cp scripts/teardown.sh ${{targets.contextdir}}/usr/local/bin/
      cp scripts/runtime-gdb.py ${{targets.contextdir}}/usr/local/bin/

      # Template
      cp templates/podTemplate.json ${{targets.contextdir}}/etc/neuvector/templates/podTemplate.json
      touch ${{targets.contextdir}}/usr/local/bin/.nvcontainer

      # symlink
      ln -sf /usr/bin/opa ${{targets.contextdir}}/usr/local/bin/opa
      ln -sf /bin/consul ${{targets.contextdir}}/usr/local/bin/consul

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\-.*'
  github:
    identifier: neuvector/neuvector
    strip-prefix: v

test:
  pipeline:
    - runs: |
        controller --help 2>&1 |pcregrep -M 'START.*\nUsage'
