#nolint:git-checkout-must-use-github-updates,valid-pipeline-git-checkout-tag
package:
  name: neuvector-sigstore-interface
  version: 0_git20240520
  epoch: 2
  description: NeuVector sigstore interface for the SUSE NeuVector Container Security Platform
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/sigstore-interface
      expected-commit: db574361364ef67c9424451e64663b0297f3f031

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: sigstore-interface
      prefix: usr/local
      vendor: true

  - uses: strip

test:
  pipeline:
    - runs: |
        sigstore-interface --help

update:
  manual: true # No releases or tags
