package:
  name: neuvector-dp
  version: 5.3.2
  epoch: 0
  description: NeuVector Full Lifecycle Container Security Platform.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - gcc
      - glibc-dev
      - jansson-dev
      - jemalloc-dev
      - libnetfilter_queue-dev
      - libnfnetlink-dev
      - libpcap-dev
      - make
      - pcre2-dev
      - pkgconf
      - userspace-rcu-dev
      - vectorscan-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/neuvector
      tag: v${{package.version}}
      expected-commit: edbdcba632835d56dcc92ba86323c8a196471289

  - runs: |
      export CFLAGS="$CFLAGS -DRCU_MEMBARRIER=true -I${PWD}/dp"
      export LDFLAGS="$LDFLAGS -lurcu-memb -no-pie"
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        make -C dp -f Makefile_arm64 CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS"
      else
        make -C dp CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS"
      fi
      mkdir -p ${{targets.contextdir}}/usr/local/bin
      install -Dm755 dp/dp ${{targets.contextdir}}/usr/local/bin/dp

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\-.*'
  github:
    identifier: neuvector/neuvector
    strip-prefix: v
