package:
  name: neuvector-monitor
  version: 5.3.2
  epoch: 3
  description: NeuVector Full Lifecycle Container Security Platform.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - gcc
      - glibc-dev
      - make

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/neuvector
      tag: v${{package.version}}
      expected-commit: edbdcba632835d56dcc92ba86323c8a196471289

  - runs: |
      make -C monitor
      mkdir -p ${{targets.contextdir}}/usr/local/bin
      install -Dm755 monitor/monitor ${{targets.contextdir}}/usr/local/bin/monitor

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\-.*'
  github:
    identifier: neuvector/neuvector
    strip-prefix: v
