package:
  name: newrelic-infrastructure-agent
  version: 1.48.4
  epoch: 0
  description: New Relic Infrastructure Agent
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/infrastructure-agent
      tag: ${{package.version}}
      expected-commit: a125c5ec08d51e375d6432b8c44e9d5c78f4af5c

  - uses: go/bump
    with:
      deps: github.com/containerd/containerd@v1.7.11 github.com/docker/docker@v24.0.7 golang.org/x/net@v0.17.0

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter: https://github.com/newrelic/infrastructure-agent/blob/07ab68f181e25a1552588a3953167e0b15f52372/build/build.mk#L20-L22
      unset LDFLAGS

      GOOS=$(go env GOOS) GOARCH=$(go env GOARCH)

      make OS=linux GOARCH=${GOARCH} compile
      make OS=linux GOARCH=${GOARCH} dist

      mkdir -p ${{targets.destdir}}/usr/bin

      install -m755 -D ./dist/${GOOS}-newrelic-infra_${GOOS}_${GOARCH}/newrelic-infra "${{targets.destdir}}"/usr/bin/newrelic-infra
      install -m755 -D ./dist/${GOOS}-newrelic-infra-service_${GOOS}_${GOARCH}/newrelic-infra-service "${{targets.destdir}}"/usr/bin/newrelic-infra-service
      install -m755 -D ./dist/${GOOS}-newrelic-infra-ctl_${GOOS}_${GOARCH}/newrelic-infra-ctl "${{targets.destdir}}"/usr/bin/newrelic-infra-ctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/infrastructure-agent
