package:
  name: nghttp2
  version: 1.59.0
  epoch: 0
  description: "experimental HTTP/2 client, server and library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - libev-dev
      - openssl-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/nghttp2/nghttp2/releases/download/v${{package.version}}/nghttp2-${{package.version}}.tar.xz
      expected-sha256: fdc9bd71f5cf8d3fdfb63066b89364c10eb2fdeab55f3c6755cd7917b2ec4ffb

  - uses: autoconf/configure
    with:
      opts: --enable-app

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "nghttp2-dev"
    description: "headers for nghttp2"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nghttp2

  - name: "nghttp2-doc"
    description: "documentation for nghttp2"
    pipeline:
      - uses: split/manpages

  - name: "libnghttp2-14"
    description: "nghttp2 client library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libnghttp2.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 8651
