package:
  name: npm
  version: 10.8.1
  epoch: 0
  description: "the npm package manager for javascript, mainline"
  copyright:
    - license: Artistic-2.0

environment:
  contents:
    packages:
      - build-base
      - rsync
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://registry.npmjs.org/npm/-/npm-${{package.version}}.tgz
      expected-sha512: 0e9d42e92bd2318408ed81eaff2da5f78baf23ee7d12a6eed44a6e2901d0f29d7ab715d1b918ade601f72e769a824d9a5c322383f22bbbda5dd396e79de2a077
      delete: true

  - runs: |
      # Wrapper scripts written in Bash and CMD.
      rm bin/npm bin/npx bin/*.cmd
      rm README.md

      # HTML docs
      rm -rf docs

  - working-directory: /home/build/node_modules
    runs: |
      find . -type f \( \
             -name '.*' -o \
             -name '*.cmd' -o \
             -name '*.bat' -o \
             -name '*.map' -o \
             -name '*.md' -o \
             \( -name '*.ts' -a ! -name '*.d.ts' \) -o \
             -name 'AUTHORS*' -o \
             -name 'LICENSE*' -o \
             -name 'license' -o \
             -name 'node-gyp' -o \
             -name 'Makefile' -o \
             -name 'README*' -o \
             -name 'readme.markdown' \) -delete

      rm -rf ./*/.git* ./*/doc ./*/docs ./*/examples ./*/scripts ./*/test
      rm -rf node_modules/node-gyp

      find . -type f -executable  -exec chmod -x {} \;

  - working-directory: /home/build/man
    runs: |
      for f in man5/folders.5 man5/install.5 man7/*.7; do
        sec=${f##*.}
        name=$(basename $f .$sec)
        title=$(echo "$name" | tr '[:lower:]' '[:upper:]')

        sed -Ei "s/^\.TH \"$title\"/.TH \"NPM-$title\"/" "$f"
        mv "$f" "${f%/*}/npm-$name.$sec"
      done

  - runs: |
      destdir="${{targets.destdir}}"/usr/lib/node_modules/npm
      install -dDm755 "$destdir"
      rsync -av --exclude melange-out /home/build/ "$destdir"
      chmod 755 "$destdir"

  - working-directory: ${{targets.destdir}}/usr/bin
    runs: |
      ln -s ../lib/node_modules/npm/bin/npm-cli.js npm
      ln -s ../lib/node_modules/npm/bin/npx-cli.js npx

  - working-directory: ${{targets.destdir}}/usr/share
    runs: |
      mv "${{targets.destdir}}"/usr/lib/node_modules/npm/man man
      ln -s ../../../share/man "${{targets.destdir}}"/usr/lib/node_modules/npm/man

subpackages:
  - name: "npm-doc"
    description: "npm documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  ignore-regex-patterns:
    - -v # ignore versions that start contain a -v, e.g. arborist-v7.2.1, libnpmfund-v4.2.0
  github:
    identifier: npm/cli
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - nodejs
    environment:
      HOME: /home/build
  pipeline:
    - runs: |
        npm --version
        npm install -g cowsay
        cowsay Yay! It works!
