package:
  name: nuclei
  version: 3.1.7
  epoch: 0
  description: "yaml based vulnerability scanner"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - go
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      destination: nuclei
      expected-commit: 1f38d6b45967ea7ee1082245df8eb9192be5e556
      repository: https://github.com/projectdiscovery/nuclei
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/quic-go/quic-go@v0.40.1
      modroot: nuclei
      go-version: "1.21"

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin && cd nuclei
      go mod edit -replace=github.com/mholt/archiver@v3.1.1+incompatible=github.com/mholt/archiver/v3@v3.3.2 # CVE-2019-10743 Fixed
      go mod tidy
      go build cmd/nuclei/main.go
      cp main "${{targets.destdir}}"/usr/bin/nuclei

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: projectdiscovery/nuclei
