package:
  name: numactl
  version: 2.0.17
  epoch: 0
  description: NUMA support for Linux
  copyright:
    - license: GPL-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numactl/numactl
      tag: v${{package.version}}
      expected-commit: c1165896572b74e971d817909bf652066ddf801a

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "numactl-doc"
    description: "numactl documentation"
    pipeline:
      - uses: split/manpages

  - name: "numactl-dev"
    description: "numactl dev"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: numactl/numactl
    strip-prefix: v
