package:
  name: nvidia-device-plugin
  version: 0.17.0
  epoch: 0
  description: NVIDIA device plugin for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d475b2cfcf12b983a4975d4fc59d91af432cf28e
      repository: https://github.com/NVIDIA/k8s-device-plugin
      tag: v${{package.version}}

  - runs: |
      make
      mkdir -p ${{targets.destdir}}/usr/bin
      mv config-manager ${{targets.destdir}}/usr/bin/
      mv nvidia-device-plugin ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: NVIDIA/k8s-device-plugin
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - runs: |
        config-manager --help
        nvidia-device-plugin --version
        nvidia-device-plugin --help
