package:
  name: ollama
  version: 0.1.41
  epoch: 1
  description: Get up and running with Llama 2 and other large language models locally
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ollama/ollama
      tag: v${{package.version}}
      expected-commit: 476fb8e89242720a7cdd57400ba928de4dde9cc1

  - runs: |
      go generate ./...
      CGO_ENABLED=1 go build -ldflags '-linkmode external -extldflags "-static"' .
      mkdir -p ${{targets.destdir}}/usr/bin
      mv ollama ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: ollama/ollama
    strip-prefix: v
