package:
  name: opensearch-2
  version: 2.11.1
  epoch: 2 # Remove CVE-2022-45146 patch when bumping to 2.12 or later
  description:
  copyright:
    - paths:
        - "*"
      attestation:
      license: Apache-2.0
  dependencies:
    runtime:
      - bash # some helper scripts use bash
      - openjdk-11-jre

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle
      - openjdk-11

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/opensearch-project/OpenSearch
      tag: ${{package.version}}
      expected-commit: 6b1986e964d440be9137eba1413015c31c5a7752

  - uses: patch
    with:
      # Patch from: https://patch-diff.githubusercontent.com/raw/opensearch-project/OpenSearch/pull/10297.patch
      patches: CVE-2022-45146.patch

  - runs: |
      export LANG=en_US.UTF-8
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk

      gradle localDistro --parallel -Dbuild.snapshot="false" -Dbuild.version_qualifier=""

      mkdir -p ${{targets.destdir}}/usr/share/opensearch/logs

      install -dm777 ${{targets.destdir}}/usr/share/opensearch/
      mv build/distribution/local/opensearch-${{package.version}}/bin/ ${{targets.destdir}}/usr/share/opensearch
      mv build/distribution/local/opensearch-${{package.version}}/lib/ ${{targets.destdir}}/usr/share/opensearch
      mv build/distribution/local/opensearch-${{package.version}}/config/ ${{targets.destdir}}/usr/share/opensearch
      mv build/distribution/local/opensearch-${{package.version}}/modules/ ${{targets.destdir}}/usr/share/opensearch
      mv build/distribution/local/opensearch-${{package.version}}/plugins/ ${{targets.destdir}}/usr/share/opensearch

      # Grab the docker entrypoint from the source tree
      mv ./distribution/docker/src/docker/bin/docker-entrypoint.sh  ${{targets.destdir}}/usr/share/opensearch/bin

      mv ./distribution/docker/src/docker/config/opensearch.yml ./distribution/docker/src/docker/config/log4j2.properties ${{targets.destdir}}/usr/share/opensearch/config

      # Set permissions to read/write the config dir
      chmod -R 755 ${{targets.destdir}}/usr/share/opensearch/

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in ${{targets.destdir}}/usr/share/opensearch/bin/*; do
        name=$(basename $i)
        ln -sf /usr/share/opensearch/bin/$name ${{targets.destdir}}/usr/bin/$name
      done

      # Manually set this to docker: https://github.com/opensearch-project/OpenSearch/blob/5f8193021215cd6979fde66474ec8d74d32ac91a/distribution/docker/src/docker/Dockerfile#LL49C90-L49C129
      sed -i -e 's/OPENSEARCH_DISTRIBUTION_TYPE=tar/OPENSEARCH_DISTRIBUTION_TYPE=docker/'  ${{targets.destdir}}/usr/share/opensearch/bin/opensearch-env

update:
  enabled: true
  github:
    identifier: opensearch-project/OpenSearch
