package:
  name: opentelemetry-collector-contrib
  version: 0.102.0
  epoch: 2
  description: Contrib repository for the OpenTelemetry Collector
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-collector-contrib
      tag: v${{package.version}}
      expected-commit: 6b1d3dd2c0c0812ebf5d973cda27f3817c68d038

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/collector/config/configgrpc@v0.102.1
      modroot: ./cmd/otelcontribcol

  - uses: go/build
    with:
      modroot: ./cmd/otelcontribcol
      packages: .
      output: otelcol-contrib
      go-package: go

subpackages:
  - name: opentelemetry-collector-contrib-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/otelcol-contrib ${{targets.subpkgdir}}/otelcol-contrib

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-collector-contrib
    strip-prefix: v
