package:
  name: parseable
  version: 1.2.0
  epoch: 0
  description: "Parseable is a log analytics system built for high throughput log ingestion cases."
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/parseablehq/parseable
      tag: v${{package.version}}
      expected-commit: 36aa929bc2f4fdef7e6c286207c42f670003962f

  - runs: |
      cargo build --release
      install -Dm755 target/release/parseable "${{targets.destdir}}"/usr/bin/parseable

  - uses: strip

update:
  enabled: true
  github:
    identifier: parseablehq/parseable
    strip-prefix: v
