package:
  name: protoc-gen-go
  version: 1.34.1
  epoch: 2
  description: Go support for Google's protocol buffers
  copyright:
    - license: BSD-3-Clause

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/protocolbuffers/protobuf-go
      tag: v${{package.version}}
      expected-commit: 4a76e11653e368b9331815e1eb98e0cedc28997f

  - uses: go/build
    with:
      packages: ./cmd/protoc-gen-go
      modroot: .
      output: protoc-gen-go

  - uses: strip

update:
  enabled: true
  github:
    identifier: protocolbuffers/protobuf-go
    strip-prefix: v
