package:
  name: protoc-gen-go-grpc
  version: 1.4.0
  epoch: 0
  description: Go support for Google's protocol buffers services
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc/grpc-go
      tag: cmd/protoc-gen-go-grpc/v${{package.version}}
      expected-commit: 1958fcbe2ca8bd93af633f11e97d44e567e945af

  - uses: go/build
    with:
      packages: .
      modroot: ./cmd/protoc-gen-go-grpc
      output: protoc-gen-go-grpc

  - uses: strip

update:
  enabled: true
  github:
    identifier: grpc/grpc-go
    strip-prefix: cmd/protoc-gen-go-grpc/v
    tag-filter: cmd/protoc-gen-go-grpc/
    use-tag: true

test:
  pipeline:
    - runs: |
        protoc-gen-go-grpc --version
