package:
  name: py3-tomli
  version: 2.0.1
  epoch: 6
  description: "TOML parser"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hukkin/tomli.git
      tag: ${{package.version}}
      expected-commit: 36ef51d6a5a55e0eca077b58695390d041061bd4

  - runs: |
      pip install --prefix=/usr --root="${{targets.contextdir}}" .

  - uses: strip

update:
  enabled: true
  github:
    identifier: hukkin/tomli

test:
  pipeline:
    - uses: python/import
      with:
        import: tomli
