package:
  name: py3-udev
  version: 0.24.3
  epoch: 1
  description: Python bindings to libudev
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - eudev
      - py3-setuptools
      - python3

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 5df7045aaa95e4b923c9a2f64fd5115b3642a69f
      repository: https://github.com/pyudev/pyudev
      tag: v${{package.version}}

  - runs: |
      python3 setup.py build
      python3 setup.py install \
        --skip-build \
        --prefix=/usr \
        --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: pyudev/pyudev
    use-tag: true
    strip-prefix: 'v'
