package:
  name: py3-parsing
  version: 3.1.2
  epoch: 2
  description: "The pyparsing module is an alternative approach to creating and executing simple grammars, vs. the traditional lex/yacc approach, or the use of regular expressions. "
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pyparsing/pyparsing.git
      tag: ${{package.version}}
      expected-commit: 7d4bda2743ebc04f68d2594bc4fffc70cd65848f

  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/pyparsing-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: pyparsing/pyparsing
    strip-prefix: pyparsing_

test:
  pipeline:
    - uses: python/import
      with:
        import: pyparsing
