package:
  name: py3-sympy
  version: "1.12"
  epoch: 0
  description: Computer algebra system (CAS) in Python
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-mpmath
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8059df7394f648bf4be5a51752e6d343003c92e6
      repository: https://github.com/sympy/sympy
      tag: sympy-${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: sympy/sympy
    strip-prefix: sympy-
