package:
  name: py3-packaging
  version: "24.1"
  epoch: 0
  description: "core utilities for python3 packaging"
  copyright:
    - license: Apache-2.0 AND BSD-2-Clause
  dependencies:
    runtime:
      - py3-parsing
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-parsing
      - py3-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/packaging.git
      tag: ${{package.version}}
      expected-commit: 85442b8032cb7bae72866dfd7782234a98dd2fb7

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: pypa/packaging
