package:
  name: py3-googleapis-common-protos
  version: 1.63.1
  epoch: 0
  description: Common protobufs used in Google APIs
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - protobuf
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/googleapis/python-api-common-protos
      expected-commit: fffb8fa9d6a84c0181982b9c3930c5b110a7408b
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: googleapis/python-api-common-protos
    strip-prefix: v
