package:
  name: py3-mpmath
  version: 1.3.0
  epoch: 0
  description: Python library for arbitrary-precision floating-point arithmetic
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b5c04506ef0cd4a1f1213f8389ee21c9c3551582
      repository: https://github.com/mpmath/mpmath
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: mpmath/mpmath
