package:
  name: py3-pythran
  version: 0.16.0
  epoch: 0
  description: Ahead of Time compiler for numeric kernels
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - numpy
      - py3-beniget
      - py3-gast
      - py3-ply
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/serge-sans-paille/pythran
      tag: ${{package.version}}
      expected-commit: 911df86403063014466f7a0a6e8667458ee90c17

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  ignore-regex-patterns:
    - .post1
  enabled: true
  github:
    identifier: serge-sans-paille/pythran
    use-tag: true
