package:
  name: py3-ujson
  version: 5.10.0
  epoch: 0
  description: "Ultra fast JSON decoder and encoder written in C with Python bindings."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-setuptools-scm
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ultrajson/ultrajson
      tag: ${{package.version}}
      expected-commit: 59875e089937c8b05c2f4b474530e3a9ec706a56

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/ujson-${{package.version}}-*.whl
      install -Dm644 LICENSE.txt \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: ultrajson/ultrajson
