package:
  name: py3-markupsafe
  version: 2.1.4
  epoch: 0
  description: "Implements a XML/HTML/XHTML Markup safe string"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/M/MarkupSafe/MarkupSafe-${{package.version}}.tar.gz
      expected-sha512: f9abe713349ee81eb0d89c584b665440f7e9c26df3f4f87e277894aa59090cfa769e099a12b16c9029d98257dbb311e49a1d7deeeb4ca9e1863fd38e574b2d94

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3918
