package:
  name: py3.10-google-cloud-sdk
  version: 427.0.0
  epoch: 3
  description: "Google Cloud Command Line Interface"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      # Required for cyclic redunancy check (gsutil help crcmod)
      - py3.10-crcmod
      - python-3.10

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3.10-setuptools
      - python-3.10
      - python-3.10-dev
      - wolfi-base

pipeline:
  - if: ${{build.arch}} == "x86_64"
    uses: fetch
    with:
      uri: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-426.0.0-linux-x86_64.tar.gz
      expected-sha256: c653a8ac1e48889005fd00e2de580a27be5a3cb46ceccc570146982c4ddf4245
      strip-components: 0

  - if: ${{build.arch}} == "aarch64"
    uses: fetch
    with:
      uri: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-426.0.0-linux-arm.tar.gz
      expected-sha256: 8409b8cc00f0ae8089be97d8a565f4072eada890776345bccb988bcd4d4bb27f
      strip-components: 0

  - runs: |
      ./google-cloud-sdk/install.sh -q
      mkdir -p ${{targets.destdir}}/usr/share/

      # Trim some extra stuff
      rm -rf google-cloud-sdk/platform/bundledpythonunix/
      rm -rf google-cloud-sdk/deb
      rm -rf google-cloud-sdk/rpm
      rm google-cloud-sdk/install.bat
      rm google-cloud-sdk/data/cli/gcloud.json

      # Remove any third party tests that bloat up the package
      find google-cloud-sdk -type d \( -name 'tests' -o -name 'test' \) -path '*/third_party/*' -exec rm -rf {} +

      # This is a large binary with vulnerabilities in it, users can add it back later.
      google-cloud-sdk/bin/gcloud components remove anthoscli

      # This is a large binary with vulnerabilities in it, users can add it back later.
      google-cloud-sdk/bin/gcloud components remove gcloud-crc32c

      # Running gcloud adds a bunch of pyc files, remove those
      find google-cloud-sdk/ -name "*.pyc" -exec rm -rf '{}' +
      rm -rf google-cloud-sdk/.install

      mv google-cloud-sdk ${{targets.destdir}}/usr/share/

      mkdir -p ${{targets.destdir}}/usr/bin
      for f in anthoscli bq docker-credential-gcloud gcloud gcloud-crc32c git-credential-gcloud.sh gsutil java_dev_appserver.sh; do
        ln -sf /usr/share/google-cloud-sdk/bin/$f ${{targets.destdir}}/usr/bin/$f
      done

  - uses: strip

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/cloud-sdk-docker
    strip-prefix: v
    use-tag: true
