package:
  name: py3.12-setuptools
  version: 70.0.0
  epoch: 0
  description: Easily download, build, install, upgrade, and uninstall Python packages
  copyright:
    - license: "MIT"
  dependencies:
    provides:
      - py3-setuptools=${{package.full-version}}
    runtime:
      - python-3.12

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3.12
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: f211a66637b8fa059bb28183da127d4e86396c991a942b028c6650d4319c3fd0
      uri: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

update:
  enabled: true
  shared: true
  release-monitor:
    identifier: 4021
