package:
  name: py3.10-crcmod
  version: "1.7"
  epoch: 1
  description: Cyclic Redundancy Check (CRC) implementation in Python
  copyright:
    - license: 'MIT'
  dependencies:
    runtime:
      - python-3.10

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3.10-setuptools
      - python-3.10
      - python-3.10-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/c/crcmod/crcmod-${{package.version}}.tar.gz
      expected-sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e

  - runs: |
      python setup.py build

  - runs: |
      python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 12017
