package:
  name: pylint
  version: 3.2.2
  epoch: 0
  description: A static code analyser for Python 2 and 3
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - py3-astroid
      - py3-dill
      - py3-isort
      - py3-platformdirs
      - py3-tomlkit
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pylint-dev/pylint
      tag: v${{package.version}}
      expected-commit: 769ffd20bbf321a6cf23f5e7221a0b8221f51482

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: pylint-dev/pylint
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        pylint --version |grep ${{package.version}}
