#nolint:git-checkout-must-use-github-updates,valid-pipeline-git-checkout-tag
package:
  name: rancher-kontainer-driver-metadata-2.9
  version: 0_git20241031
  epoch: 0
  description: Complete container management platform - kontainer driver metadata
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-kontainer-driver-metadata=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/kontainer-driver-metadata/
      branch: release-v2.9
      expected-commit: 14e0dc4331af537cc0de3cc740bf00b4c50b21ab

  - runs: |
      mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata
      install -Dm755 data/data.json  ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata/data.json

test:
  pipeline:
    - runs: |
        # check the expected files are available at the expected location at `/var/lib/rancher-data/driver-metadata/`
        test -f /var/lib/rancher-data/driver-metadata/data.json

update:
  enabled: true
  git: {}
  schedule:
    period: daily
    reason: Commit at head of branch moves frequently
