package:
  name: readline
  version: "8.2"
  epoch: 6
  description: "GNU readline library"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/readline/readline-${{package.version}}.tar.gz
      expected-sha256: 3feb7171f16a84ee82ca18a36d7b9be109a52c04f492a053331d7d1095007c35

  - uses: patch
    with:
      patches: fix-rl_do_undo-crash.patch
      strip-components: 0

  - uses: patch
    with:
      patches: fix-ncurses-underlinking.patch
      strip-components: 0

  - uses: patch
    with:
      patches: readline82-001.patch readline82-002.patch readline82-003.patch readline82-004.patch readline82-005.patch readline82-006.patch readline82-007.patch readline82-008.patch readline82-009.patch readline82-010.patch
      strip-components: 0

  - name: Configure
    runs: |
      # Needed to ensure ncurses linked
      export LDFLAGS=$(echo $LDFLAGS | sed 's/,--as-needed//g')
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "readline-dev"
    description: "GNU readline headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - readline

update:
  enabled: true
  release-monitor:
    identifier: 4173
