package:
  name: readline
  version: "8.2"
  epoch: 3
  description: "GNU readline library"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz
      expected-sha256: f8ceb4ee131e3232226a17f51b164afc46cd0b9e6cef344be87c65962cb82b02

  - uses: patch
    with:
      patches: readline81-001.patch
      strip-components: 0

  - uses: patch
    with:
      patches: readline81-002.patch
      strip-components: 0

  - uses: patch
    with:
      patches: fix-ncurses-underlinking.patch
      strip-components: 0

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "readline-dev"
    description: "GNU readline headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - readline

update:
  enabled: true
  release-monitor:
    identifier: 4173
