package:
  name: redka
  version: 0.5.1
  epoch: 0
  description: Redis re-implemented with SQLite
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nalgeon/redka
      expected-commit: f631c08f30bca0e27c490bc4bb2ee27acf4a2df8
      tag: v${{package.version}}

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv build/redka ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: nalgeon/redka
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - redis-cli
  pipeline:
    - runs: |
        redka&
        sleep 2
        redis-cli ping
        killall redka
