package:
  name: rekor
  version: 1.3.4
  epoch: 2
  description: Software Supply Chain Transparency Log
  copyright:
    - license: Apache-2.0
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/rekor
      tag: v${{package.version}}
      expected-commit: 5072901241fc6370a78457219e7aa2da490f399f

subpackages:
  - name: ${{package.name}}-server
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/rekor-server
          output: rekor-server
          ldflags: -w
          # GHSA-2c7c-3mj9-8fqh
          deps: github.com/go-jose/go-jose/v3@v3.0.1 golang.org/x/crypto@v0.17.0
      - uses: strip

  - name: ${{package.name}}-cli
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/rekor-cli
          output: rekor-cli
          ldflags: -w
          # GHSA-2c7c-3mj9-8fqh
          deps: github.com/go-jose/go-jose/v3@v3.0.1
      - uses: strip

  - name: ${{package.name}}-backfill-redis
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/backfill-redis
          output: backfill-redis
          ldflags: -w
      - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/rekor
    strip-prefix: v
