package:
  name: ruby3.2-faraday
  version: 2.9.1
  epoch: 0
  description: HTTP/REST API client library.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.2-faraday-net_http
      - ruby3.2-ruby2_keywords

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4abafa5c66ce75bc2abbf0a5e7e98137dea91eb2
      repository: https://github.com/lostisland/faraday
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: faraday

update:
  enabled: true
  github:
    identifier: lostisland/faraday
    strip-prefix: v
