package:
  name: s6
  version: 2.13.0.0
  epoch: 0
  description: "skarnet.org's small & secure supervision software suite."
  copyright:
    - license: ISC
  dependencies:
    runtime:
      - execline
  scriptlets:
    trigger:
      paths:
        - /run/service
      script: |
        #!/bin/execlineb -P
        s6-svscanctl -an /run/service

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - execline-dev
      - skalibs-dev
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://skarnet.org/software/s6/s6-${{package.version}}.tar.gz
      expected-sha256: 7e46f8f55d80bb0e2025a64d5d649af4a4ac21e348020caaadde30ba5e5b4830

  - name: Configure
    runs: |
      ./configure \
        --enable-shared \
        --enable-static \
        --disable-allstatic \
        --libdir=/usr/lib \
        --libexecdir=/lib/s6 \
        --with-dynlib=/lib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "s6-dev"
    description: "s6 development headers"
    pipeline:
      - uses: split/dev

  - name: "s6-ipcserver"
    description: "s6 ipcserver"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin

          for i in s6-ipcserver s6-ipcserver-socketbinder s6-ipcserverd s6-applyuidgid; do
            mv "${{targets.destdir}}"/bin/$i "${{targets.subpkgdir}}"/bin/$i
          done

update:
  enabled: true
  release-monitor:
    identifier: 5485
