package:
  name: sccache
  version: 0.7.6
  epoch: 0
  description: sccache is ccache with cloud storage
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mozilla/sccache
      tag: v${{package.version}}
      expected-commit: 794c987b7843f404b9e50513dae978f807ba0a60

  - runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin
      mv target/release/sccache ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: mozilla/sccache
    strip-prefix: v
