package:
  name: simdjson
  version: 3.9.3
  epoch: 0
  description: Parses Gigabytes of JSON per second
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ee8515122d6b7973522afce7131e57062a4ad30b
      repository: https://github.com/simdjson/simdjson/
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DBUILD_SHARED_LIBS=ON \
        -DSIMDJSON_BUILD_STATIC_LIB=ON \

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: simdjson-static
    pipeline:
      - uses: split/static
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/lib/cmake/simdjson-static/
          mv ${{targets.destdir}}/usr/lib/cmake/simdjson/simdjson_staticTargets-minsizerel.cmake ${{targets.contextdir}}/usr/lib/cmake/simdjson-static/
          mv ${{targets.destdir}}/usr/lib/cmake/simdjson/simdjson_staticTargets.cmake ${{targets.contextdir}}/usr/lib/cmake/simdjson-static/
    description: simdjson static

  - name: simdjson-dev
    pipeline:
      - uses: split/dev
    description: simdjson dev

update:
  enabled: true
  github:
    identifier: simdjson/simdjson
    strip-prefix: v
    tag-filter: v
