package:
  name: skaffold
  version: 2.12.0
  epoch: 1
  description: Easy and Repeatable Kubernetes Development
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f386e6c552e83c3a9445fe34442aaed8dd381ab3
      repository: https://github.com/GoogleContainerTools/skaffold
      tag: v${{package.version}}

  - runs: |
      make
      install -m755 -D ./out/skaffold "${{targets.destdir}}"/usr/bin/skaffold

  - uses: strip

update:
  enabled: true
  github:
    identifier: GoogleContainerTools/skaffold
    strip-prefix: v
    tag-filter: v
