package:
  name: skalibs
  version: 2.14.2.0
  epoch: 0
  description: "set of general-purpose C programming libraries for skarnet.org software"
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://skarnet.org/software/skalibs/skalibs-${{package.version}}.tar.gz
      expected-sha256: ddfec5730e5b2f19d0381ecf7f796b39a6e473236bda0ad8d3776a3fe7b07e43

  - name: Configure
    runs: |
      ./configure \
        --enable-shared \
        --enable-static \
        --libdir=/usr/lib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "skalibs-dev"
    description: "skalibs development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/skalibs
          mv "${{targets.destdir}}"/usr/lib/skalibs/sysdeps "${{targets.subpkgdir}}"/usr/lib/skalibs/

update:
  enabled: true
  release-monitor:
    identifier: 5486
