package:
  name: skopeo
  version: 1.14.1
  epoch: 1
  description: Work with remote images registries - retrieving information, images, signing content
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: b174ada87751ecd7f8e0e292d163c9b0c4a2172a6ba32e1725ae272c24f7f841
      uri: https://github.com/containers/skopeo/archive/v${{package.version}}/v${{package.version}}.tar.gz

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - runs: |
      CGO_ENABLED=0 go build -mod=vendor \
        -tags "exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" \
        -trimpath -ldflags "-s -w -extldflags -static -buildid=" \
        -o "${{targets.destdir}}/usr/bin/skopeo" ./cmd/skopeo

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 9216
