package:
  name: slsa-verifier
  version: 2.5.1
  epoch: 7
  description: Verify provenance from SLSA compliant builders
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/slsa-framework/slsa-verifier
      tag: v${{package.version}}
      expected-commit: eb7007070baa04976cb9e25a0d8034f8db030a86

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v24.0.9 golang.org/x/net@v0.23.0 github.com/sigstore/cosign/v2@v2.2.4 google.golang.org/protobuf@v1.33.0 github.com/cloudflare/circl@v1.3.7 github.com/go-jose/go-jose/v3@v3.0.3 gopkg.in/go-jose/go-jose.v2@v2.6.3
      modroot: .

  - uses: go/build
    with:
      packages: ./cli/slsa-verifier
      modroot: .
      output: slsa-verifier
      ldflags: -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}} -X sigs.k8s.io/release-utils/version.gitCommit=$(git rev-parse HEAD) -X sigs.k8s.io/release-utils/version.buildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: slsa-framework/slsa-verifier
    strip-prefix: v
