package:
  name: snappy-java
  version: 1.1.10.5
  epoch: 1
  description: Snappy compressor/decompressor for Java
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl
      - openjdk-8
      - openjdk-8-default-jvm
      - samurai
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/xerial/snappy-java
      expected-commit: 08abfa4f85b3a39c5fe8fa2f43b482440bedb5a3
      tag: v${{package.version}}

  - runs: |
      make
      mkdir -p "${{targets.destdir}}"/usr/share/java/snappy-java
      cp target/snappy-java-*.jar "${{targets.destdir}}"/usr/share/java/snappy-java/snappy-java.jar

update:
  enabled: true
  github:
    identifier: xerial/snappy-java
    strip-prefix: v
