package:
  name: sqlpad
  version: 7.4.1 # when updating check the patch below as it contains dependency version updates which may downgrade if upstream upgrades them
  epoch: 5
  description: Web-based SQL editor. Legacy project in maintenance mode.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs-18 # currently needs node 18, to check in the future see, https://github.com/sqlpad/sqlpad/blob/master/.nvmrc
      - yarn

environment:
  contents:
    packages:
      - build-base
      - busybox
      - jq
      - nodejs-18
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlpad/sqlpad
      expected-commit: 5929bbb5ca78e187952673f454a84aabe80e304a
      tag: v${{package.version}}

  - working-directory: /home/build/server
    runs: |
      # Upgrade mysql2 to mitigate CVE-2024-21508
      yarn upgrade mysql2@3.9.7

      # Create "resolutions" section of package.json
      jq '.resolutions |= (if . then . else {} end)' package.json > temp.json && mv temp.json package.json
      for override in '"semver"="6.3.1"' '"@node-saml/node-saml"="4.0.5"' '"ip"="2.0.1"' '"jose"="4.15.5"' '"xlsx"="https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz"' '"tar"="6.2.1"' '"mysql2"="3.9.7"'; do
        jq ".resolutions.${override}" package.json > temp.json && mv temp.json package.json
      done

      for dep in '"express"="4.19.2"'; do
        jq ".dependencies.${dep}" package.json > temp.json && mv temp.json package.json
      done

      yarn install

  - uses: patch
    with:
      patches: build-sh.patch

  - runs: |
      ./scripts/build.sh
      mkdir -p ${{targets.destdir}}/usr/bin
      mv server ${{targets.destdir}}/usr/bin/sqlpad-server

      # Remove files adding unnecessary shebang deps: dtrace and groovy
      rm ${{targets.destdir}}/usr/bin/sqlpad-server/node_modules/cassandra-driver/Jenkinsfile
      rm ${{targets.destdir}}/usr/bin/sqlpad-server/node_modules/ldapjs/examples/snoopldap.d

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/app
          ln -s /usr/bin/sqlpad-server ${{targets.subpkgdir}}/usr/app

update:
  enabled: true
  github:
    identifier: sqlpad/sqlpad
    strip-prefix: v
