package:
  name: starship
  version: 1.19.0
  epoch: 0
  description: "The minimal, blazing-fast, and infinitely customizable prompt for any shell!"
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/starship/starship
      tag: v${{package.version}}
      expected-commit: de2c4a63553568adcba95432acfbe36080cc6be8

  - runs: |
      cargo build --release
      install -Dm755 target/release/starship "${{targets.destdir}}"/usr/bin/starship

  - uses: strip

update:
  enabled: true
  github:
    identifier: starship/starship
    strip-prefix: v

test:
  pipeline:
    - runs: |
        starship --version
