package:
  name: statsd
  version: 0.10.2
  epoch: 0
  description: Daemon for easy but powerful stats aggregation
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0e20be57d4918dadf5b5fad61b5c61ef382f8860
      repository: https://github.com/statsd/statsd
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/src/app
      cp *.js ${{targets.destdir}}/usr/src/app
      cp *.json ${{targets.destdir}}/usr/src/app
      for d in backends bin lib servers test utils; do
        cp -r $d ${{targets.destdir}}/usr/src/app
      done

  - runs: |
      # Set graphite hostname to "graphite"
      sed -i 's/graphite.example.com/graphite/' exampleConfig.js
      mv exampleConfig.js ${{targets.destdir}}/usr/src/app/config.js

update:
  enabled: true
  github:
    identifier: statsd/statsd
    use-tag: true
    strip-prefix: v
