package:
  name: step
  version: 0.25.2
  epoch: 0
  description: A zero trust swiss army knife for working with X509, OAuth, JWT, OATH OTP, etc.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/cli
      tag: v${{package.version}}
      expected-commit: 4f55cda9ed13d64c70a6e0b17e06ab600c73831a

  - uses: go/build
    with:
      packages: ./cmd/step
      output: step
      ldflags: -s -w -X main.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: smallstep/cli
    strip-prefix: v
