package:
  name: strace
  version: "6.9"
  epoch: 0
  description: Diagnostic, debugging and instructional userspace tracer
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      # - elfutils-dev TODO
      - gawk

pipeline:
  - uses: fetch
    with:
      expected-sha256: da189e990a82e3ca3a5a4631012f7ecfd489dab459854d82d8caf6a865c1356a
      uri: https://github.com/strace/strace/releases/download/v${{package.version}}/strace-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --enable-mpers=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: strace-doc
    pipeline:
      - uses: split/manpages
    description: strace manpages

update:
  enabled: true
  github:
    identifier: strace/strace
    strip-prefix: v
