package:
  name: stress-ng
  version: 0.18.00
  epoch: 0
  description: "stress-ng will stress test a computer system in various selectable ways"
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - keyutils-dev
      - kmod-dev
      - libaio-dev
      - libatomic
      - libattr1
      - libbsd-dev
      - libcap-dev
      - libgcrypt-dev
      - libjpeg-turbo-dev
      - libjudy-dev
      - libsctp-dev
      - xxhash-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ColinIanKing/stress-ng
      tag: V${{package.version}}
      expected-commit: ea5b6cd62237b07318809ec9f2070eac1329f7cb

  - uses: autoconf/make
    with:
      opts: LDFLAGS=-static

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: ColinIanKing/stress-ng
    strip-prefix: V
