package:
  name: supercronic
  version: 0.2.29
  epoch: 7
  description: Cron for containers
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aptible/supercronic
      tag: v${{package.version}}
      expected-commit: 538ad7df148e8b265a8c2db42db6492b55abe463

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0
      modroot: .

  - uses: go/build
    with:
      packages: .
      modroot: .
      output: supercronic
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

update:
  enabled: true
  github:
    identifier: aptible/supercronic
    strip-prefix: v
