package:
  name: syft
  version: 0.100.0
  epoch: 1
  description: CLI tool and library for generating a Software Bill of Materials from container images and filesystems
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/syft
      tag: v${{package.version}}
      expected-commit: a16a4ad6c993aaaa1ec502667c215b0e8c8e51ff

  - uses: go/build
    with:
      ldflags: -w -X main.version=${{package.version}}
      output: syft
      packages: ./cmd/syft

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/syft
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        syft --version
