package:
  name: tekton-pipelines
  version: 0.60.2
  epoch: 0
  description: A cloud-native Pipeline resource.
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tektoncd/pipeline
      tag: v${{package.version}}
      expected-commit: ee3af64bed9f2762034fc10d38d9531224b9df9a
      destination: tekton

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.0.2
      modroot: tekton

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: tekton-pipelines-controller
      modroot: tekton
      vendor: true

data:
  - name: cmds
    items:
      entrypoint: entrypoint
      events: events
      nop: nop
      resolvers: resolvers
      sidecarlogresults: sidecarlogresults
      webhook: webhook
      workingdirinit: workingdirinit

subpackages:
  - range: cmds
    name: tekton-pipelines-${{range.key}}
    description: tekton pipelines ${{range.key}}
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/${{range.key}}
          output: tekton-pipelines-${{range.key}}
          modroot: tekton

update:
  enabled: true
  github:
    identifier: tektoncd/pipeline
    strip-prefix: v
