package:
  name: terragrunt
  version: 0.58.14
  epoch: 0
  description: Thin wrapper for Terraform providing extra tools
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 72889647cad710b8fee850cc6853e98be80ea6a5
      repository: https://github.com/gruntwork-io/terragrunt
      tag: v${{package.version}}

  - runs: |
      go build -v -o bin/terragrunt -ldflags "-s -w -X  github.com/gruntwork-io/go-commons/version.Version=v${{package.version}}"
      install -Dm755 bin/terragrunt "${{targets.contextdir}}"/usr/bin/terragrunt

  - uses: strip

test:
  pipeline:
    - name: Verify terragrunt
      runs: |
        terragrunt --version

update:
  enabled: true
  github:
    identifier: gruntwork-io/terragrunt
    strip-prefix: v
    use-tag: true
    tag-filter: v
