package:
  name: terraform-provider-azurerm
  version: 3.105.0
  epoch: 1
  description: Terraform provider for Azure Resource Manager
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:
      - terraform
      - terraform-compat
      - terraform-local-provider-config

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a0a6640349623f1130da1677a1ff998f65c54451
      repository: https://github.com/hashicorp/terraform-provider-azurerm
      tag: v${{package.version}}

  - uses: go/build
    with:
      output: terraform-provider-azurerm
      packages: .
      vendor: "true"

  - runs: |
      GOARCH=$(go env GOARCH)
      mkdir -p "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/azurerm/${{package.version}}/linux_${GOARCH}/
      ln -s "${{targets.destdir}}"/usr/bin/terraform-provider-azurerm \
          "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/azurerm/${{package.version}}/linux_${GOARCH}/terraform-provider-azurerm_v${{package.version}}_x5

update:
  enabled: true
  github:
    identifier: hashicorp/terraform-provider-azurerm
    strip-prefix: v
