package:
  name: tflint
  version: 0.51.1
  epoch: 0
  description: A Pluggable Terraform Linter
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 96dce7684ce71844462f0fc725289f85da086639
      repository: https://github.com/terraform-linters/tflint
      tag: v${{package.version}}

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv dist/tflint ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: terraform-linters/tflint
    use-tag: true
    strip-prefix: v
