package:
  name: tflint
  version: 0.50.2
  epoch: 0
  description: A Pluggable Terraform Linter
  copyright:
    - license: MPL 2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fa9fb0a6a8b85c478ffb1d5c05beaad653026787
      repository: https://github.com/terraform-linters/tflint
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7
      go-version: "1.21.1"

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv dist/tflint ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: terraform-linters/tflint
    use-tag: true
    strip-prefix: v
