package:
  name: thanos
  version: 0.35.1
  epoch: 1
  description: Highly available Prometheus setup with long term storage capabilities.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 086a698b2195adb6f3463ebbd032e780f39d2050
      repository: https://github.com/thanos-io/thanos
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0

  - runs: |
      make build

  - runs: |
      install -Dm755 "$(go env GOPATH)"/bin/thanos "${{targets.destdir}}"/usr/bin/thanos

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - rc*
  github:
    identifier: thanos-io/thanos
    strip-prefix: v
    tag-filter: v
