package:
  name: timestamp-authority
  version: 1.2.1
  epoch: 0
  description: RFC3161 Timestamp Authority
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/timestamp-authority
      tag: v${{package.version}}
      expected-commit: 81cbb69f9afda8a63551c8e380f1f5f653398426

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/go-jose/go-jose/v3@v3.0.1

  - runs: |
      make timestamp-cli timestamp-server

  - uses: strip

subpackages:
  - name: ${{package.name}}-server
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ./bin/timestamp-server ${{targets.subpkgdir}}/usr/bin/

  - name: ${{package.name}}-cli
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ./bin/timestamp-cli ${{targets.subpkgdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: sigstore/timestamp-authority
    strip-prefix: v
