package:
  name: trivy
  version: 0.52.0
  epoch: 2
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c24dfbab68056a42aff9589b024c6f2d067f9f52
      repository: https://github.com/aquasecurity/trivy
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/trivy
      output: trivy
      ldflags: -X github.com/aquasecurity/trivy/pkg/version.ver=${{package.version}}

test:
  environment:
    contents:
      packages:
        - jq
  pipeline:
    - name: Check trivy version
      runs: |
        trivy version
        trivy version | grep '^Version: ${{package.version}}$'
    - name: Check trivy version as JSON
      runs: |
        trivy version -f json | jq -M
        [ "$(trivy version -f json 2>/dev/null | jq -r .Version)" == "${{package.version}}" ]

update:
  enabled: true
  github:
    identifier: aquasecurity/trivy
    strip-prefix: v
