package:
  name: trurl
  version: "0.13"
  epoch: 0
  description: 'trurl is a command line tool for URL parsing and manipulation.'
  copyright:
    - license: curl

environment:
  contents:
    packages:
      - build-base
      - busybox
      - curl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/curl/trurl
      tag: trurl-${{package.version}}
      expected-commit: 811d1d202ae6a54b85aa285e919ac1e8a0b45e66

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "trurl-doc"
    description: "documentation for trurl"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  version-separator: _
  github:
    identifier: curl/trurl
    strip-prefix: trurl-

test:
  pipeline:
    - runs: |
        trurl --version
        trurl --url https://curl.se/we/are.html --get '{port}'
