package:
  name: uv
  version: 0.2.9
  epoch: 0
  description: An extremely fast Python package installer and resolver, written in Rust.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssl-dev
      - perl
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/uv
      tag: ${{package.version}}
      expected-commit: e9fc99e6229a91dcebe668dab648b2b6b3ccf81a

  - runs: |
      cargo build --locked --release
      install -Dm755 target/release/uv "${{targets.destdir}}"/usr/bin/uv

  - uses: strip

update:
  enabled: true
  github:
    identifier: astral-sh/uv

test:
  pipeline:
    - runs: |
        uv --version | grep ${{package.version}}
