package:
  name: wabt
  version: 1.0.35
  epoch: 0
  description: The WebAssembly Binary Toolkit
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - python3
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/WebAssembly/wabt
      tag: ${{package.version}}
      expected-commit: 39f85a791cbbad91a253a851841a29777efdc2cd

  - runs: git submodule update --init

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: wabt-static
    pipeline:
      - uses: split/static
    description: wabt static

  - name: wabt-dev
    pipeline:
      - uses: split/dev
    description: wabt dev

update:
  enabled: true
  github:
    identifier: WebAssembly/wabt
