package:
  name: wasi-libc
  version: 21.0.0
  epoch: 0
  description: "WASI libc implementation for WebAssembly"
  copyright:
    - license: Apache-2.0 WITH LLVM-exception AND Apache-2.0 AND MIT AND CC0-1.0 AND BSD-2-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - clang-17
      - clang-17-dev
      - llvm17
      - make
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/WebAssembly/wasi-libc/archive/refs/tags/wasi-sdk-21.tar.gz
      expected-sha256: 4a2a3e3b120ba1163c57f34ac79c3de720a8355ee3a753d81f1f0c58c4cf6017

  - name: Build
    runs: |
      CC=clang  make

  - runs: make INSTALL_DIR="${{targets.destdir}}/usr/share/wasi-sysroot" install

  - uses: strip

update:
  enabled: true
  manual: true # version in fetch URL is different from package version
  github:
    identifier: WebAssembly/wasi-libc
    strip-prefix: wasi-sdk-
    use-tag: true
