package:
  name: wasm-tools
  version: 1.209.1
  epoch: 0
  description: "Low level tooling for WebAssembly in Rust"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libLLVM-15
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wasm-tools
      tag: v${{package.version}}
      expected-commit: c8fcb7075da08a8a2d8b3fb14b091b4fd340b3a9

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasm-tools ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wasm-tools
    strip-prefix: v
    tag-filter: v
