package:
  name: wolfictl
  version: 0.16.15
  epoch: 0
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: 1f3b9362efb340de4f25012c704481f4850048da

  - uses: go/bump
    with:
      deps: github.com/mholt/archiver/v3@v3.5.1
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2

  - uses: go/build
    with:
      packages: .
      output: wolfictl

  - uses: strip

test:
  pipeline:
    - name: Verify wolfictl
      runs: |
        wolfictl version

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
