package:
  name: xz
  version: 5.4.5
  epoch: 1
  description: "Library and CLI tools for XZ and LZMA compressed files"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://tukaani.org/xz/xz-${{package.version}}.tar.gz
      expected-sha256: 135c90b934aee8fbc0d467de87a05cb70d627da36abe518c357a873709e5b7d6

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "xz-dev"
    description: "xz headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xz

  - name: "xz-doc"
    description: "xz documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 5277
