package:
  name: ytt
  version: 0.47.0
  epoch: 0
  description: YAML templating tool that works on YAML structure instead of text
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: fetch
    with:
      expected-sha256: 71641bdc5086c97c9d8c098f5f42fc29e725b33a89488fbefcaa2dad4664dad7
      uri: https://github.com/carvel-dev/ytt/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: go/build
    with:
      packages: ./cmd/ytt
      output: ytt
      ldflags: -w -X github.com/vmware-tanzu/carvel-ytt/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: carvel-dev/ytt
    strip-prefix: v
