package:
  name: zarf
  version: 0.42.1
  epoch: 0
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1e906ffee49f31366fffc0150c85417e82ef5c38
      repository: https://github.com/zarf-dev/zarf
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/mholt/archiver/v3@v3.5.2
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2
      show-diff: true

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/zarf-dev/zarf/src/config.CLIVersion=v${{package.version}}'
      output: zarf
      packages: .

  - uses: strip

test:
  pipeline:
    - runs: |
        zarf version || grep ${{package.version}}
        zarf --help

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
