package:
  name: zig
  version: 0.12.0
  epoch: 2
  description: "General-purpose programming language designed for robustness, optimality, and maintainability"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - clang-17
      - clang-17-dev
      - cmake
      - libstdc++
      - libxml2-dev
      - llvm-lld-17
      - llvm-lld-17-dev
      - llvm-lld-17-static
      - llvm17
      - llvm17-dev
      - samurai
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ziglang/zig
      tag: ${{package.version}}
      expected-commit: a685ab1499d6560c523f0dbce2890dc140671e43

  - runs: |
      export LDFLAGS="$LDFLAGS,--copy-dt-needed-entries"
      CC=clang CXX=clang LD=llvm-lld cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_PREFIX_PATH=/usr \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DZIG_VERSION="${{package.version}}" \
        -DZIG_SHARED_LLVM=ON \
        -DZIG_TARGET_MCPU=baseline

      # Limit builds to one core because it uses a lot of memory
      cmake --build build -j$(nproc)

      # Workaround for missing zig binary in the build dir.
      DESTDIR="build/.dest" cmake --install build

      cd build
      ./.dest/usr/bin/zig build docs

      cd ..
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

update:
  enabled: true
  github:
    identifier: ziglang/zig
    use-tag: true
