package:
  name: zot
  version: 2.0.0
  epoch: 2
  description: A production-ready vendor-neutral OCI-native container image registry (purely based on OCI Distribution Specification)
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - go-1.20

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c2196e3ae1625b87b9bdd3ed002466b71c51fc20
      repository: https://github.com/project-zot/zot
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/containerd/containerd@v1.7.11 github.com/go-git/go-git/v5@v5.11.0 github.com/cloudflare/circl@v1.3.7
      go-version: "1.20"

  - runs: |
      GOARCH=$(go env GOARCH)

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy binary
      install -m755 -D ./bin/zot-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zot

      make -o modcheck OS=linux ARCH=${GOARCH} modtidy cli
      install -m755 -D ./bin/zli-linux-${GOARCH} "${{targets.destdir}}"/usr/bin/zli

  - uses: strip

update:
  enabled: true
  github:
    identifier: project-zot/zot
    strip-prefix: v
