name: Bump go deps to a certain version

# Leave go off here, some packages pin to an older version. Let's just assume this gets injected elsewhere.
needs:
  packages:
    - git
    - gobump

inputs:
  deps:
    description: The deps to bump, space separated
    required: true
  modroot:
    description: The root of the module
    default: .
  go-version:
    description: "The go version to set the go.mod syntax to"
    default: ""
  replaces:
    description: "The replaces to add to the go.mod file"

pipeline:
  - runs: |
      cd "${{inputs.modroot}}"

      # We use the --tidy flag to run go mod tidy before and after in some cases (if old versions of go are used, we need to update the go.mod format)
      gobump --packages "${{inputs.deps}}" --replaces "${{inputs.replaces}}" --tidy --go-version=${{inputs.go-version}}

      if [ -d "./vendor" ]; then
        go mod vendor
      fi
