name: Wolfictl Lint

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

permissions:
  contents: read

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    if: github.repository == 'wolfi-dev/os'

    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    # this need to point to main to always get the latest action
    - uses: wolfi-dev/actions/wolfictl-lint@main # main
