name: Wolfictl Check Updates

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

permissions:
  contents: read

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@d6babd6899969df1a11d14c368283ea4436bca78 # v44.5.2
      with:
        separator: ' '
        files: "*.yaml"
        files_ignore: ".yam.yaml"

    - name: Check
      id: check
      # this need to point to main to always get the latest action
      uses: wolfi-dev/actions/wolfictl-check-updates@main # main
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        changed_files: ${{ steps.files.outputs.all_changed_files }}
