name: Wolfictl Check Updates

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@716b1e13042866565e00e85fd4ec490e186c4a2f #tj-actions/changed-files@v41.0.1
      with:
        separator: ' '
        files: "*.yaml"
        files_ignore: ".yam.yaml"

    - name: Check
      id: check
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:4c9087d2c2fccf2c0f3470cfa695c605bc0dcd7bcbb1ee9c64f80f62d8e1cfdc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: wolfictl
        args: check update ${{ steps.files.outputs.all_changed_files }}
